### ISSUE TITLE
Release mismatch happens on iOS devices

### ISSUE THREAD

**Issue by Mike1707** [getsentry/sentry-cordova#100]
Hey Guys,

I have quite a similar issue as in #61.  After building my Ionic project with `ionic cordova build ios` an auto-release with all sourcemaps will be uploaded as expected.

`Sentry: running before_compile - set SENTRY_SKIP_AUTO_RELEASE=true to skip this
Uploading assets release: '90b1fd86b917dd69644a' path: /Users/mike/Developer/collarcare/cc-ionic/platforms/ios/www`

Afterwards, I can see this release `90b1fd86b917dd69644a` with all sourcemaps in the sentry.io dashboard.

Now, I test two cases. 

1) When I use `ionic serve --lab` and an error happens in the browser, all works as expected and the issue will be reported in release `90b1fd86b917dd69644a` and the sourcemaps/stacktrace work fine.

<img width="2246" alt="bildschirmfoto 2018-11-09 um 14 33 48" src="https://user-images.githubusercontent.com/10029709/48265350-98ea8380-e42c-11e8-89c0-9c377657f094.png">

2) When I start my emulator/iOS-Device with the new build, the same error is thrown but now the issue will not be reported in release `90b1fd86b917dd69644a`. Instead in release `myBundleId-1.0.2` as stated in the config.xml.

<img width="2241" alt="bildschirmfoto 2018-11-09 um 14 48 10" src="https://user-images.githubusercontent.com/10029709/48266101-aa348f80-e42e-11e8-82fe-d79551fbc58f.png">

Unfortunately, sourcemaps are not working now. I tried to upload them with the sentry-cli using `sentry-cli releases -o ORG -p PROJ files myBundleId-1.0.2 upload-sourcemaps www/build
`

Then, the sourcemaps are in the artifacts section, but as you can see above, they does not work.

<img width="460" alt="bildschirmfoto 2018-11-09 um 14 40 19" src="https://user-images.githubusercontent.com/10029709/48265690-70af5480-e42d-11e8-9260-8f7eaaff2188.png">

I would appreciate any help!

Thanks
Mike

My Init-Method and ErrorHandler: 

```
Sentry.init({
  dsn: 'https://FOO@sentry.io/FOO',
});

export class SentryIonicErrorHandler extends IonicErrorHandler {
  handleError(error) {
    super.handleError(error);
    try {
      Sentry.captureException(error.originalError || error);
    } catch (e) {
      console.error(e);
    }
  }
}
```

Ionic Info: 
```
Ionic:

   ionic (Ionic CLI)  : 4.3.1 (/Users/mike/.nvm/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/mike/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v10.11.0 (/Users/mike/.nvm/versions/node/v10.11.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by Mike1707** [comment]
It seems the bug has been fixed with the recent update. However, it works now :-)

**Comment by HazAT** [comment]
:)
Closing this since it works now.
