### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by neilbo** [getsentry/sentry-cordova#102]
Getting an error when trying to build XCode project with Sentry (Ionic 3 project)

![screen shot 2018-11-15 at 12 08 56 pm](https://user-images.githubusercontent.com/1586394/48529968-553ac280-e8e1-11e8-89e4-38b070992cbf.png)

`
Reading property from path/to/sentry.properties
env: node: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
`

`
ionic info 
`

`
cli packages: (/path/to/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 6.4.0 browser 5.0.4 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v8.11.1
    npm               : 6.1.0
    OS                : macOS High Sierra
    Xcode             : Xcode 10.1 Build version 10B61

Environment Variables:

    ANDROID_HOME : /Users/username/Library/Android/sdk
`

**Comment by neilbo** [comment]
managed to fix this by

`ln -s $(eval which node) /usr/local/bin/node`

**Comment by HazAT** [comment]
Hey, thanks for posting your solution. Closing this now since your errors seem to be resolved.

**Comment by xyyhello** [comment]
thanks @neilbo  answer solved it

**Comment by mukarramali** [comment]
@neilbo I owe you

**Comment by bondseid** [comment]
Fixed thanks!
