### ISSUE TITLE
<unlabeled event> in UICompatibilityInputViewController

### ISSUE THREAD

**Issue by rebeccafae** [getsentry/sentry-cordova#108]
We are seeing thousands of errors that all show the following message:
```
message: <unlabeled event> UICompatibilityInputViewController
```

There is also a warning shown:
```
There was 1 error encountered while processing this event
exception: Discarded invalid value
Reason: No 'type' or 'value' present
Value: {values: [{stacktrace: {frames: []}, thread_id: 99}]}
```

Seeing this on iOS12 and 11.
sentry-cordova version 0.13.1

**Comment by wcjord** [comment]
We've gotten a similar error though it does have a label - NSInvalidArgumentException
https://sentry.io/share/issue/1f81da1dd93d4f30ba3d3b5e5e9cade7/
