### ISSUE TITLE
Android sentry error submissions all returning 404

### ISSUE THREAD

**Issue by Dukeman330** [getsentry/sentry-cordova#11]
I've got the Cordova plugin installed and it seems to be working fine on iOS - I've been able to fire of some simulated and actual errors and they get captured by Sentry. On Android, however, any time my app tries to submit an error to Sentry it throws a 404. Specifically, I've tried:

`Sentry.getSharedClient().captureException(new Error('something bad happened'))`

and

`Sentry.getSharedClient().captureMessage('uh oh')`

These fire off a POST request to:

`https://sentry.io/api/[MY APP ID]/store/?sentry_version=7&sentry_client=raven-js%2F3.22.1&sentry_key=[MY SENTRY KEY]`

except it contains my actual app ID and key - every time, I get a 404 Not Found. Is this a bug or did I do something wrong in my config?

**Comment by Dukeman330** [comment]
So, I believe I found the issue: I needed to whitelist sentry for cordova to make the outbound requests by adding:

`<access origin="sentry.io" />`

to my config.xml. I'm pretty sure the whitelist is a standard feature of a default cordova or ionic app - might be worth noting this in the Sentry plugin documentation?

Also, are there any other domains that the sentry plugin may use that I should similarly whitelist?

**Comment by HazAT** [comment]
Oh, thank you for pointing this out. I will release an update for this.

**Comment by HazAT** [comment]
I've added a section in the docs
https://docs.sentry.io/clients/cordova/#configuration
Thank you for highlighting this.

**Comment by Dukeman330** [comment]
Great - thanks! Just a heads up, there's a typo in:

> Keep in mind if you use an on premise installtion, adjust this domain accordingly.
