### ISSUE TITLE
Can't build with xcode: can't find sentry.properties

### ISSUE THREAD

**Issue by MyC-Greg** [getsentry/sentry-cordova#114]
Hi,

The build are fine with android and ios platforms on the command line but fails with xcode giving this error:

> # Reading property from myAppPath/sentry.properties
> env: node: No such file or directory
> Command PhaseScriptExecution failed with a nonzero exit code

I use  
```
"ionic-angular": "3.9.2" 
"sentry-cordova": "^0.13.1"
```

It fails in debug and release configurations. Any thoughts @HazAT  ? It looks like the comment from 
@RaulTsc in issue #12  https://github.com/getsentry/sentry-cordova/issues/12#issuecomment-386210387

**Comment by Anuj-logiciel** [comment]
Hii @MyC-Greg - You can try removing platform and re-add. This will solve your problem.
I solved with following steps.This is caused when sentry is not properly added in platform.
Steps - 
-  Remove Your installed plugin
- Remove platform
- Add Sentry Plugin
- Add Platform 
PROBLEM SOLVED. Thanks!
