### ISSUE TITLE
[__NSCFConstantString sentry_sanitize]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by FbPalmabit** [getsentry/sentry-cordova#117]
App iOS build successfully but crash with error:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString sentry_sanitize]: unrecognized selector sent to instance 0x1d5217c90'`

**Comment by wcjord** [comment]
This is very likely related to this error - https://github.com/getsentry/sentry-cordova/issues/111

I believe this needs a fix in the source code.

**Comment by ErnestStaug** [comment]
I am having the same issue. Had to uninstall. :)
