### ISSUE TITLE
iOS in release build not sending events until restarting app

### ISSUE THREAD

**Issue by yosikal** [getsentry/sentry-cordova#119]
On iOS, release 0.13.1, using captureException will not shoot the event immediately but only after App is restarted. From reading the SentryCordova.m code it seem like this behavior is "by design" but I don't understand why. Most errors on Cordova apps will not crash the app while there might be large number of errors not reported because the user won't open the app again.

**Comment by luis02lopez** [comment]
I'm experimenting the same issue.
Where I can read that state that this behaviour is by design? and how can we prevent it?

**Comment by dmitryrn** [comment]
Same here

**Comment by dmitryrn** [comment]
@yosikal Can you please explain where in [SentryCordova.m](https://github.com/getsentry/sentry-cordova/blob/master/src/ios/SentryCordova.m) this behaviour is performed? (I not a an Objective-C guy and do not where this is)

**Comment by dmitryrn** [comment]
Wow, I updated sentry-cordova from 0.12.3 to 0.16.2 and seems events capturing immediately, not when app restarted. It fixed for me
