### ISSUE TITLE
Doesn't work with compile

### ISSUE THREAD

**Issue by bayssmekanique** [getsentry/sentry-cordova#122]
When running command `cordova compile`, an error is thrown at line `48` of the `before_compile.js` script: https://github.com/getsentry/sentry-cordova/blob/8e5eb67b22d6dfc0996d9f9c9ac7efb70ce93866/scripts/before_compile.js#L48

```shell
$ cordova "compile" "--release" "--device" "ios" "android" "--buildConfig" "--buildFlag=-UseModernBuildSystem=0"
Sentry: running before_compile - set SENTRY_SKIP_AUTO_RELEASE=true to skip this
Cannot read property 'map' of undefined
cordova build failed, error: exit status 1
```

This works fine when using `cordova build`, but we can't use `build` as we perform steps between `prepare` and `compile`.

**Comment by ashiwakoti** [comment]
@bayssmekanique I am running into the same issue. Did you find a workaround for this error?
