### ISSUE TITLE
Breaking: Cordova 9 Support missing

### ISSUE THREAD

**Issue by tmk1991** [getsentry/sentry-cordova#126]
requireCordovaModule is deprecated in Cordova 9. Plugins using requireCordovaModule will fail to install. Affected plugins will throw the following error during installation.

`CordovaError: Using "requireCordovaModule" to load non-cordova module "xcode" is not supported. Instead, add this module to your dependencies and use regular "require" to load it`

https://ionic.zendesk.com/hc/en-us/articles/360021400494-Package-build-fails-with-error-CordovaError-Using-requireCordovaModule-

**Comment by tmk1991** [comment]
Hi - @HazAT  - It seems you're the main contributor here. Is this something that can be patched? Looking forward to getting started with Sentry!

**Comment by mitsuhiko** [comment]
@tmk1991 which version of sentry-cordova are you using? We are no longer using `requireCordovaModule`: https://github.com/getsentry/sentry-cordova/commit/8e5eb67b22d6dfc0996d9f9c9ac7efb70ce93866

**Comment by Polm90** [comment]
same issue here...
i'm running cordova 9. i'm installing sentry-cordova@0.12.3 as reported in the documentation (in "getting-started" in the project panel).
I've tried with version 0.15.0 but the wizard stucks in connection so the installation doesn't terminate.

**Comment by Yuripetusko** [comment]
Works fine on 0.15.0 for me

**Comment by marcogrieco** [comment]
Which is the solution?

**Comment by bruno-garcia** [comment]
We plan to bump to Cordova 10 on the next release

**Comment by jennmueng** [comment]
@bruno-garcia Looks like this was already fixed as we don't use that API anymore following 8e5eb67.

Looks like @Polm90's issue was with the wizard and not the SDK.

Weird that it doesn't work for @rafwell as it works fine on v9 and v10 for me. Maybe an incorrect installation/update? I've had a lot of friction with Cordova's build tools these past couple days.
