### ISSUE TITLE
Adding Plugin for iOS

### ISSUE THREAD

**Issue by ish2028** [getsentry/sentry-cordova#128]
I get the following warning, but I am not using ionic in my script to build my project.  After running the following commands
`cordova platform add ios android`
`cordova build --release --device ios android`

```***********************************************
Sentry - Warning
https://docs.sentry.io/clients/cordova/ionic/
***********************************************
You've run this command with the ionic prefix
either run it without 'ionic' or do run:
$ sentry-wizard
See: https://github.com/getsentry/sentry-wizard
***********************************************
***********************************************
```

Anyone have this issue?

**Comment by tobiasmuecksch** [comment]
I have the same issue. Please send a mail to the support, as issues on this repo are answered very rarely.....

See:
https://github.com/getsentry/sentry-cordova/issues/112

**Comment by HazAT** [comment]
Hey, so does it do anything harmful or is it just showing the warning?
We show this warning if `process.stdin.isTTY` is false, which OS are you running this on?

**Comment by tobiasmuecksch** [comment]
macOS: 10.14.5
NodeJS: v11.12.0
Cordova 9.0.0

For me the problem is, that I clone my app's git repo. Then after `npm i` I try to add iOS. The problem is, that the failing installation of the sentry plugin interrupts the plugin installation and some plugins, that should be installed afterwards, do not install.
Anyways, the problem is also, that we cannot select the app's correct sentry project.

**Comment by HazAT** [comment]
You should be able to work around this by creating the `sentry.properties` file manually you put into your project root.

Content:
```
defaults.url=https://sentry.io/
defaults.org=sentry-test
defaults.project=cordova
auth.token=<TOKEN>
cli.executable=node_modules/@sentry/cli/bin/sentry-cli

```

**Comment by tobiasmuecksch** [comment]
I will report back after the next build, maybe at the end of this week

**Comment by tobiasmuecksch** [comment]
@HazAT Nope, it didn't work. We still cannot correctly add any cordova platforms because of this issue. Workarounds shouldn't be desirable anyways.

**Comment by tobiasmuecksch** [comment]
@HazAT anything new on this issue?
