### ISSUE TITLE
Can't set release on iOS

### ISSUE THREAD

**Issue by bnxio** [getsentry/sentry-cordova#130]
I am unable to set the `release` for iOS app builds.

App is built using Ionic

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0
   Ionic Framework    : ionic-angular 3.9.6
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 9.0.1-nightly.2019.5.22.7c4b0927 (cordova-lib@9.0.2-nightly.2019.5.22.dbab1acb)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\Ben\Android\SDK)
   NodeJS            : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
``` 

Followed the ionic documentation and everything works flawlessly on Android (inc sourcemaps).

Using Jenkins we're setting the `release` like `A.B.C (BUILD)` - since the default release string displayed can stay constant between many builds (e.g. `com.domain.app-1.0.13`) it isn't useful. 

During the build process we edit our `SentryErrorHandler` and set the `release` part of `Sentry.init`. This works on Android, but not iOS where the default release string still applies.

```
Sentry.init({ 
    dsn: '...',
    release: 'preBuild' // This get's edited
});
```

I have tried editing `src/ios/SentryCordova.m` specifically `setReleaseVersionDist` for example:
```
     if (event.extra[@"__sentry_dist"]) {
         event.dist = [NSString stringWithFormat:@"%@", event.extra[@"__sentry_dist"]];
     }
     event.releaseName = "1.0.13 (12345)";
     event.sdk = @{@"name": SentryCordovaSdkName,
                   @"version": SentryCordovaVersionString,
                   @"integrations": @[@"sentry-cocoa"]};
```

But this is still not sent to Sentry, e.g.:
```
{
  "event_id": "e57dbef9ea5d400786ec917ec111d086",
  "project": 3,
  "release": "com.domain.app-1.0.13",
  "dist": "10403",
  "platform": "cocoa",
  "message": "",
  "datetime": "2019-05-23T08:35:55.000000Z",
}
```

Does anyone have any suggestions why `release` is being ignored on iOS?

Many Thanks!

**Comment by bnxio** [comment]
I never figured out why `sentry-cordova` wasn't setting the `release` but I've got the `src/ios/SentryCordova.m` patch to work reliably now, so I'll close this.

**Comment by mjsarfatti** [comment]
@bnxio care to share what you did?
