### ISSUE TITLE
Support for electron

### ISSUE THREAD

**Issue by Polm90** [getsentry/sentry-cordova#133]
On Electron we get the same error we get on Browser: "Missing command Error" (at line 58 in breadcrumbs.js)

**Comment by tobiasmuecksch** [comment]
@Polm90 there is a [sentry-electron](https://github.com/getsentry/sentry-electron) repo, especially for electron. Please use this one.

**Comment by Polm90** [comment]
The sentry-electron repo is for "native" electron...
I was referring to the cordova-electron platform
