### ISSUE TITLE
Sentry Cordova issue tracking: native code

### ISSUE THREAD

**Issue by Polm90** [getsentry/sentry-cordova#134]
When I look at an issue recorded from cordova (on an iOS device) I see that the origin is in "app:///[native code] " instead of my js file that originated it.
Which is a useless info: I can't easily debug it.

Am I doing something wrong?
Thank you

**Comment by casyalex** [comment]
same issue, does it need sourcemap or anything else?

**Comment by HazAT** [comment]
Is it for all frames or just for a few?

**Comment by Polm90** [comment]
all

**Comment by tomfebry** [comment]
I am having the exact same issue

**Comment by uptownjimmy** [comment]
We are having the same issue. This is possibly a deal breaker for our team. When will this bug be assigned/fixed/deployed?

**Comment by HazAT** [comment]
Are you using Ionic v4 with Capacitor instead of Cordova?
This would explain it, we do currently not support Capacitor.

**Comment by Polm90** [comment]
I'm using Cordova 9.0.0

**Comment by HazAT** [comment]
https://github.com/getsentry/sentry-cordova/issues/162#issuecomment-551420138

Also

https://github.com/getsentry/sentry-cordova/issues/154#issuecomment-551421634

Can’t provide a better answer right now :/

**Comment by uptownjimmy** [comment]
> Are you using Ionic v4 with Capacitor instead of Cordova?
> This would explain it, we do currently not support Capacitor.

We are using Cordova 9.0.0
