### ISSUE TITLE
Cordova build auto-release

### ISSUE THREAD

**Issue by Polm90** [getsentry/sentry-cordova#135]
I noticed that when we use the command "cordova build" sentry auto-generates a release version (giving an hash). However, in my code I tell sentry the real version number; so when the app raises an error, it is associated to my manual release which has no artifacts associated (because they were uploaded related to the auto-generated release).
So, what should I do to use my release version (which has a meaningful name) and the artifacts generated during the command "cordova build"?
Documentation is not very clear.

**Comment by ElianCordoba** [comment]
I found this #92
