### ISSUE TITLE
Use with vue sentry integration

### ISSUE THREAD

**Issue by andrewj-bjss** [getsentry/sentry-cordova#137]
Is it possible to use cordova-sentry and the vue integration? Ordinarily Sentry cordova is set up using something like:

    var Sentry = window.cordova.require('sentry-cordova.Sentry')
    Sentry.init({
        dsn: '[DSN]'
    })

and sentry vue installation guide says import and use like so:
 
    import * as Sentry from '@sentry/browser';
    import * as Integrations from '@sentry/integrations';

    Sentry.init({
        dsn: '[DSN],
        integrations: [new Integrations.Vue({Vue, attachProps: true})],
    });

But I'm not sure this works as a single integration. Do I effectively need to treat them as separate packages, Maybe call one CordovaSentry and leave the other as Sentry? Would I need to import and init sentry on every Vue component or can it be done in my main.js?

I'm also seeing examples where people are using Raven rather than the sentry browser package. Is it likely that I need to use Cordova Sentry and Raven together, rather than try to integrate the Sentry Browser approach?

**Comment by dineshtrivedi** [comment]
Hello @andrewj-bjss , Any update about this issue? I was wondering if you have solved it

**Comment by GeorgianaBarbut** [comment]
Hey @andrewj-bjss, I would also like to know if you solved it. Thanks!
