### ISSUE TITLE
Expected a non-empty value

### ISSUE THREAD

**Issue by devhowtobiz** [getsentry/sentry-cordova#143]
plugin version : `"sentry-cordova": "0.15.0"`
OS Version: iOS 12.2

SentryIonicErrorHandler
```
handleError(error) {
  super.handleError(error)
  try {
    Sentry.captureException(error.stack ? error : new Error(error.message || error))
  } catch (e) {...}
}
```

When I throw an error, then I see this error on Sentry console. and the raw message doesn't have any stack message
```
exception.values.0.stacktrace.frames: Discarded invalid value 
Reason | expected a non-empty value
```

It's ok on Android, only iOS get this error

**Comment by HazAT** [comment]
Can you try `0.16.0` and see if the error is gone?

**Comment by kenho1703** [comment]
Hi Daniel,

Thank for the information, I have upgraded sentry-cordova to 0.16.0, but
source map still not working, a link to access this test event.
https://sentry.io/organizations/eztek/issues/1199962410/?project=1523626&query=is%3Aunresolved&statsPeriod=14d

I use Sentry.captureException to send event. please let me know if you have
any update.

*Thank You and Best Regards,*

*Ken Ho*

**Comment by HazAT** [comment]
What is the content you pass into `Sentry.captureException`?

**Comment by kenho1703** [comment]
For testing, I use  Sentry.captureException(new Error('test error')),

*Thank You and Best Regards,*

*Ken Ho*

**Comment by SolidplasmaStudios** [comment]
I'm having this issue on sentry.io which I'm using for crash logging. Specifically my error is `Discarded invalid value
Name: exception.values.0.stacktrace.frames
Reason: expected a non-empty value`

I'm using an extension in game maker studio from a few years back to send the errors. I had to tweak a bit of it to bring it up to date, but other than this, it works fine.
