### ISSUE TITLE
what does this plugin do that the node lib doesn't?

### ISSUE THREAD

**Issue by josh-m-sharpe** [getsentry/sentry-cordova#145]
What does this plugin do that the node lib doesn't?  In other words, why wouldn't I just use @sentry/node or @sentry/browser?  (Not cordova related, but what's the difference between those node packages as well?)

Is is possible to update the README with some relevant notes?

**Comment by HazAT** [comment]
I've added a sentence to our Docs
`This SDK is able to catch native crashes that happen on iOS or uncaught exceptions on Android as well.`

Anyway, to explain it, if you use this SDK over just `@sentry/browser` we will also handle crashes that directly happen on iOS or Android.
