### ISSUE TITLE
NSInvalidArgumentException on iOS

### ISSUE THREAD

**Issue by Polm90** [getsentry/sentry-cordova#147]
I've updated the plugin from version 0.15.0 to the latest 0.16.0.
But the app now crashes at the startup with the following exception 
"NSInvalidArgumentException
-[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x1f7e297f0"

The exception is raised before the page is loaded.
If I run the app without initializing sentry, the app works as expected without the initial crash

**Comment by coulson84** [comment]
Also suffering from this issue. I have just created a new project and am having this same problem. 

```
- (void)addBreadcrumb:(CDVInvokedUrlCommand *)command {
    [self.commandDelegate runInBackground:^{
        NSDictionary *jsonBreadcrumb = [command.arguments objectAtIndex:0];
        SentryBreadcrumb *breadcrumb = [SentryJavaScriptBridgeHelper createSentryBreadcrumbFromJavaScriptBreadcrumb:jsonBreadcrumb];
        [SentryClient.sharedClient.breadcrumbs addBreadcrumb:breadcrumb];
        CDVPluginResult *result = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsDictionary:[breadcrumb serialize]];
        [self.commandDelegate sendPluginResult:result callbackId:command.callbackId];
    }];
}
```

jsonBreadcrumb is resolving to null. Will just have to leave sentry cordova out of our build for now. 

The irony that the error reporting framework is causing a fatal and un-reportable error is certainly not lost on me

**Comment by dev-manager-uk** [comment]
We have this too.  Just signed up for sentry then found a new error in our app.  Argh!!!

**Comment by HazAT** [comment]
Please upgrade to `0.16.1` the issue should be fixed there.

**Comment by dev-manager-uk** [comment]
Thank you

**Comment by Polm90** [comment]
Version 0.16.2 doesn't throw the error anymore
