### ISSUE TITLE
Git diff on every build

### ISSUE THREAD

**Issue by WHeesters** [getsentry/sentry-cordova#149]
Hello,

I'm on sentry-cordova version 0.15.0 (on Ionic 4) and I've noticed that each time we build the project there's a difference in the index.html (release number). I was wondering if there is a way to either not change the release number/upload stuff to Sentry on a local build. Or a way to have the generated code in index.html moved to the compiled index.html of the individual platforms?

This is the generated code I'm talking about:

```
<script>
(function(w){var i=w.SENTRY_RELEASE=w.SENTRY_RELEASE||{};i.id='5e3b5876a9b6d0843722';})(this);
</script>
<!-- sentry-cordova -->
```

**Comment by elreco** [comment]
same here

**Comment by bruno-garcia** [comment]
Does this happen on v1.0.0?
