### ISSUE TITLE
Installing Plugin in Corber.io project blows up

### ISSUE THREAD

**Issue by wytlytningNZ** [getsentry/sentry-cordova#15]
```
Discovered plugin "sentry-cordova" in config.xml. Adding it to the project
Installing "sentry-cordova" for android
Error during processing of action! Attempting to revert...
Failed to install 'sentry-cordova': Error: Uh oh!
ENOENT: no such file or directory, open '/Users/josh/Documents/projects/fe/my-ember-project/corber/cordova/plugins/sentry-cordova/www/SentryCordova.js'
```

I believe it is because the generated `www` folder from `yarn dist` never gets run

**Comment by yosikal** [comment]
Hi,

Did you manage to workaround it somehow?

Thanks,
Yosi

**Comment by HazAT** [comment]
Hey, it seems like corber.io tries to install the wrong npm package.
It tries to install `sentry-cordova` but it is the wrong one, it should install `@sentry/cordova`.
Maybe try to change it in the plugin.xml (not sure if cordova supports it).
We may have to release it with also with `sentry-cordova`.

**Comment by yosikal** [comment]
I'm actually not using corber.io but Ionic 1. I was replying to this thread hoping that someone will give me some idea on how to solve this issue. 

For my problem I opened issue: https://github.com/getsentry/sentry-cordova/issues/20

**Comment by HazAT** [comment]
Hey, can you try again, I just published the package also on the name `sentry-cordova`.

**Comment by HazAT** [comment]
This should work now.
Feel free to reopen it if there is still a problem.
