### ISSUE TITLE
Capacitor Support?

### ISSUE THREAD

**Issue by josh-m-sharpe** [getsentry/sentry-cordova#154]
Does this plugin workin an Ionic v4 / Capacitor app?
If so, would it be possible to add setup documentation for Capacitor since it has to be different?

I assume the steps are (roughly):
- Install sentry-cocoa in `ios/` as defined here: https://docs.sentry.io/clients/cocoa/
- Install sentry-cordova in the `package.json`
- Android???

However both sentry-cocoa and sentry-cordova require configuration  It's not clear whether I should configure the native layer, the javascript layer or both.  Does sentry-cordova defer to sentry-cocoa?  Does Sentry-cordova's init also configure the native layer?

This is all compounded by the fact that errors aren't sent in Debug mode - so it seems I have to compile and release an app, at least in test flight, in order to attempt triggering any errors.

I have a very functional capacitor/ionic app that I'd like to add sentry to.  I'm motivated to figure out what steps are required, but most likely need support from the folks at Sentry.  I'd be happy to work with someone who can help advise and then provide some documentation/description of the final steps to set things up appropriately. 

Thanks!

**Comment by HazAT** [comment]
https://github.com/getsentry/sentry-cordova/issues/162#issuecomment-551420138

We never tried it, while we want to add support for it we do not have any capacity now to work on it.

It’s mostly probably just tinkering around until you have it running with Sentry.
Can’t provide clear instructions :/

**Comment by Sampath-Lokuge** [comment]
Hi @HazAT Any feedback about Capacitor support now?

**Comment by J3m5** [comment]
I'm interested too.

**Comment by HazAT** [comment]
Not in the near future, we are not focusing resources at Cordova right now. We accept PRs tho 😅

**Comment by ihadeed** [comment]
For anyone that's interested; I created a proposal here: https://github.com/capacitor-community/proposals/issues/32

**Comment by phal0r** [comment]
The CLI relies on cordova hooks and the cordova javascript API to perform its tasks. Both is not available in a Capacitor project. 

What I did to make it run (at least with Capacitor and Ionic React), is to
- normally install sentry-cordova via npm into an existing Capacitor project
- manually apply those build phases for iOS -> https://docs.sentry.io/platforms/javascript/guides/cordova/#ios-specifics (this is a one time task, since the xcode workspace is checked in to version control)
- add the sentry script piece into public/index.html (also one time task)
- take the important pieces from sentry cli and modified it to create releases from my Capacitor project, this is just an ordinary node.js file and can easily be integrated into CI systems (it needs to be run after `npm run build`)

In case anyone is interested in the script:
```
const createRelease = () => {
  console.log(`Sentry: running - set SENTRY_SKIP_AUTO_RELEASE=true to skip this`)
  const SentryCli = require('@sentry/cli')
  const path = require('path')
  const fs = require('fs')
  const crypto = require('crypto')

  if (process.env.SENTRY_SKIP_AUTO_RELEASE) {
    console.log('Sentry: Skipping Sentry auto release')
    return
  }

  function walk(dir) {
    let results = []
    let list = fs.readdirSync(dir)
    list.forEach((file) => {
      file = dir + '/' + file
      let stat = fs.statSync(file)
      if (stat && stat.isDirectory()) {
        results = results.concat(walk(file))
      } else {
        results.push(file)
      }
    })
    return results
  }

  const configFile = path.join('sentry.properties')
  if (!fs.existsSync(configFile)) {
    console.error('Sentry: sentry.properties does not exist in project root! ')
    process.exit(1)
    return
  }
  const ignore = ['node_modules']
  const sentryCli = new SentryCli(configFile)

  const buildPaths = [path.join(process.cwd(), 'build/static/js')]

  const allReleases = buildPaths.map((buildPath) => {
    if (!fs.existsSync(buildPath)) {
      console.error(`Sentry: build path does not exist ${buildPath}`)
      console.error('This is not an Ionic project, please check out:')
      console.error('https://docs.sentry.io/platforms/javascript/sourcemaps/')
      console.error('to find out how to correctly upload sourcemaps for your project.')
      return
    }

    const indexHtml = path.join(process.cwd(), 'build', 'index.html')
    if (!fs.existsSync(indexHtml)) {
      console.error('Sentry: index.html does not exist')
      return
    }

    // Adding files to include
    let includes = []
    walk(buildPath).forEach((file, index) => {
      let f = path.basename(file)
      let [ext2, ext1, name] = f.split('.').reverse()
      // we only want js source files and the according sourcemaps (no css etc.)
      if (ext2 === 'js' || (ext1 === 'js' && ext2 === 'map')) {
        // ignore sw-toolbox file
        if (name !== 'sw-toolbox') {
          includes.push(file)
        }
      }
    })

    const algorithm = 'sha1'
    let allHash = ''

    includes.forEach((file) => {
      let shasum = crypto.createHash(algorithm)
      shasum.update(fs.readFileSync(file))
      allHash += shasum.digest('hex')
    })

    const shasum2 = crypto.createHash(algorithm)
    shasum2.update(allHash)
    const fileHash = shasum2.digest('hex')

    let release = Promise.resolve(fileHash.slice(0, 20))
    // if the environment variable SENTRY_RELEASE_STRING is set this will be used instead of the filehash slice
    if (process.env.SENTRY_RELEASE_STRING) {
      release = Promise.resolve(process.env.SENTRY_RELEASE_STRING)
    } else if (process.env.SENTRY_RELEASE_PROPOSE_VERSION) {
      release = sentryCli.releases.proposeVersion()
    }

    return release.then((release) => {
      // we use another regex than sentry-cordova provides, because create-react-app strips out all html content
      // and therefor also the former marker for the regex
      const regex = /(SENTRY_RELEASE\|\|\{\}\)\.id=\")\w+\"/
      let contents = fs.readFileSync(indexHtml, {
        encoding: 'utf-8',
      })

      fs.writeFileSync(indexHtml, contents.replace(regex, `$1${release}"`))

      console.log(`Uploading assets release: '${release}' path: ${buildPath}`)
      return sentryCli.releases
        .new(release)
        .then(() =>
          sentryCli.releases.uploadSourceMaps(release, {
            include: includes,
            ignore: ignore,
            rewrite: true,
          })
        )
        .then(() => sentryCli.releases.finalize(release))
    })
  })

  return Promise.all(allReleases)
}

createRelease()
```

**Comment by fkirc** [comment]
> Not in the near future, we are not focusing resources at Cordova right now. We accept PRs tho

I hope that this changes in the future.
I believe that Capacitor is the future of Ionic and similar frameworks, whereas Cordova will die sooner or later.
Of course, I understand that existing Cordova-projects won't switch immediately, but there are strong architectural advantages in favor of Capacitor.

**Comment by Sampath-Lokuge** [comment]
Yes, the future is a Capacitor. It is awesome.

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-capacitor

**Comment by phal0r** [comment]
@bruno-garcia 
Do you already have a timeline for a first release?

**Comment by bruno-garcia** [comment]
We don't have a timeline yet. I suggest following the repo for now, but we'll update this issue as soon as we have news.

**Comment by jennmueng** [comment]
Closing this as we now officially support capacitor with https://github.com/getsentry/sentry-capacitor
