### ISSUE TITLE
Ionic 4/Sentry Integration

### ISSUE THREAD

**Issue by ceaheart** [getsentry/sentry-cordova#162]
I've already documented the following error in another post: 

Sentry: build path does not exist C:\Users\Chris{project name}\platforms\android\www
This is not an Ionic project, please check out:
https://docs.sentry.io/clients/javascript/sourcemaps/ 1
to find out how to correctly upload sourcemaps for your project.

My issue now is that adding Sentry to any Ionic 4 base project causes the build to fail.  I start getting really strange errors as soon as I add Sentry - 

:app:lintVitalReleaseError processing C:\Users\Chris\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.10.0\4e2c5fa04648ec9772c63e2101c53af6504e624e\jackson-core-2.10.0.jar:module-info.class: broken class file?

Exception in thread "main" java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at com.google.devtools.build.android.desugar.CoreLibraryRewriter.reader(CoreLibraryRewriter.java:44)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:388)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280) FAILED
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

Execution failed for task ':app:transformClassesWithDesugarForRelease'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\3.jar --output C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\desugar\release\5.jar --input C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\1.jar --output C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\desugar\release\3.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\CordovaLib\build\intermediates\intermediate-jars\release\classes.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\classes\release --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\0.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\1.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\2.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\3.jar --classpath_entry C:\Users\Chris\test\ionic-first-app\platforms\android\app\build\intermediates\transforms\stackFramesFixer\release\4.jar --bootclasspath_entry C:\Users\Chris\AppData\Local\Android\sdk\platforms\android-27\android.jar --bootclasspath_entry C:\Users\Chris\AppData\Local\Android\sdk\platforms\android-27\optional\org.apache.http.legacy.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\resources.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\jsse.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\jce.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\charsets.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfr.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}

Again, this is just a simple Ionic 4 app, no customizations other than adding Sentry.

**Comment by Kiludude** [comment]
I have the same issue using Cordova 8.0.0

**Comment by bhandaribhumin** [comment]
same issue 

```
Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes
Sentry: running before_compile - set SENTRY_SKIP_AUTO_RELEASE=true to skip this
Sentry: build path does not exist /Users/username/Desktop/git/project/project Mobile/platforms/android/www
This is not an Ionic project, please check out:
https://docs.sentry.io/clients/javascript/sourcemaps/
to find out how to correctly upload sourcemaps for your project.
ANDROID_HOME=/Users/username/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/
Requirements check failed for JDK 1.8
[ERROR] An error occurred while running subprocess cordova.
```

**Comment by phal0r** [comment]
The CLI relies on cordova hooks and the cordova javascript API to perform its tasks. Both is not available in a Capacitor project. 

What I did to make it run (at least with Capacitor and Ionic React), is to
- normally install sentry-cordova via npm into an existing Capacitor project
- manually apply those build phases for iOS -> https://docs.sentry.io/platforms/javascript/guides/cordova/#ios-specifics (this is a one time task, since the xcode workspace is checked in to version control)
- add the sentry script piece into public/index.html (also one time task)
- take the important pieces from sentry cli and modified it to create releases from my Capacitor project, this is just an ordinary node.js file and can easily be integrated into CI systems (it needs to be run after `npm run build`)

In case anyone is interested in the script:
```
const createRelease = () => {
  console.log(`Sentry: running - set SENTRY_SKIP_AUTO_RELEASE=true to skip this`)
  const SentryCli = require('@sentry/cli')
  const path = require('path')
  const fs = require('fs')
  const crypto = require('crypto')

  if (process.env.SENTRY_SKIP_AUTO_RELEASE) {
    console.log('Sentry: Skipping Sentry auto release')
    return
  }

  function walk(dir) {
    let results = []
    let list = fs.readdirSync(dir)
    list.forEach((file) => {
      file = dir + '/' + file
      let stat = fs.statSync(file)
      if (stat && stat.isDirectory()) {
        results = results.concat(walk(file))
      } else {
        results.push(file)
      }
    })
    return results
  }

  const configFile = path.join('sentry.properties')
  if (!fs.existsSync(configFile)) {
    console.error('Sentry: sentry.properties does not exist in project root! ')
    process.exit(1)
    return
  }
  const ignore = ['node_modules']
  const sentryCli = new SentryCli(configFile)

  const buildPaths = [path.join(process.cwd(), 'build/static/js')]

  const allReleases = buildPaths.map((buildPath) => {
    if (!fs.existsSync(buildPath)) {
      console.error(`Sentry: build path does not exist ${buildPath}`)
      console.error('This is not an Ionic project, please check out:')
      console.error('https://docs.sentry.io/platforms/javascript/sourcemaps/')
      console.error('to find out how to correctly upload sourcemaps for your project.')
      return
    }

    const indexHtml = path.join(process.cwd(), 'build', 'index.html')
    if (!fs.existsSync(indexHtml)) {
      console.error('Sentry: index.html does not exist')
      return
    }

    // Adding files to include
    let includes = []
    walk(buildPath).forEach((file, index) => {
      let f = path.basename(file)
      let [ext2, ext1, name] = f.split('.').reverse()
      // we only want js source files and the according sourcemaps (no css etc.)
      if (ext2 === 'js' || (ext1 === 'js' && ext2 === 'map')) {
        // ignore sw-toolbox file
        if (name !== 'sw-toolbox') {
          includes.push(file)
        }
      }
    })

    const algorithm = 'sha1'
    let allHash = ''

    includes.forEach((file) => {
      let shasum = crypto.createHash(algorithm)
      shasum.update(fs.readFileSync(file))
      allHash += shasum.digest('hex')
    })

    const shasum2 = crypto.createHash(algorithm)
    shasum2.update(allHash)
    const fileHash = shasum2.digest('hex')

    let release = Promise.resolve(fileHash.slice(0, 20))
    // if the environment variable SENTRY_RELEASE_STRING is set this will be used instead of the filehash slice
    if (process.env.SENTRY_RELEASE_STRING) {
      release = Promise.resolve(process.env.SENTRY_RELEASE_STRING)
    } else if (process.env.SENTRY_RELEASE_PROPOSE_VERSION) {
      release = sentryCli.releases.proposeVersion()
    }

    return release.then((release) => {
      // we use another regex than sentry-cordova provides, because create-react-app strips out all html content
      // and therefor also the former marker for the regex
      const regex = /(SENTRY_RELEASE\|\|\{\}\)\.id=\")\w+\"/
      let contents = fs.readFileSync(indexHtml, {
        encoding: 'utf-8',
      })

      fs.writeFileSync(indexHtml, contents.replace(regex, `$1${release}"`))

      console.log(`Uploading assets release: '${release}' path: ${buildPath}`)
      return sentryCli.releases
        .new(release)
        .then(() =>
          sentryCli.releases.uploadSourceMaps(release, {
            include: includes,
            ignore: ignore,
            rewrite: true,
          })
        )
        .then(() => sentryCli.releases.finalize(release))
    })
  })

  return Promise.all(allReleases)
}

createRelease()
```

**Comment by bruno-garcia** [comment]
> JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/

Android only works with JDK 8
