### ISSUE TITLE
Cordova: Too many symbol files

### ISSUE THREAD

**Issue by phuoctuong** [getsentry/sentry-cordova#166]
Hi guys, I have problem after finishing Sentry configuration. Everything goes well for my iOS App but there is one issue after I upload my app to Apple Store
I receive an email from App Store connect is **ITMS-90381: Too many symbol files** and I see there is one functionality called `Uploading Debug Symbols` and I guess the root cause is from it.

Do you guys have any solution for fixing that?

**Comment by HazAT** [comment]
This has nothing to do with our script of upload debug symbols.
Check the answer here:
https://stackoverflow.com/questions/25755240/too-many-symbol-files-after-successfully-submitting-my-apps
