### ISSUE TITLE
Version 0.15 and higher blocks all user input ionic / cordova / ios if split pane

### ISSUE THREAD

**Issue by sjdrew** [getsentry/sentry-cordova#167]
Not quite sure where to start with this issue but as soon as Sentry.init() is called, no user input works (all buttons / taps do nothing, app is basically non responsive).

This is only specific to all these conditions:
- sentry cordova 0.15.0 or higher
- Ionic 3 / cordova
- IOS / iPad 
- And If using split pane (navigation on left)  https://ionicframework.com/docs/api/split-pane

Have not been able to produce a basic app that shows this problem (yet). But wonder if any ideas on this.

If I stick with sentry 0.14.0 then all ok.

Thanks
/Steve

**Comment by jennmueng** [comment]
As this issue has not received an update for a year, will be closing for now as we've rewrote a lot with the new update: [v1.0.0-rc.0](https://github.com/getsentry/sentry-cordova/releases/tag/v1.0.0-rc.0). Please reopen if the issue pops up again in this new version!
