### ISSUE TITLE
Impossible to upload debug information files

### ISSUE THREAD

**Issue by thibautguedou3** [getsentry/sentry-cordova#168]
Hi,

I have just installed the sentry-cordova sdk to add Sentry to my project. Everything works as intended except when I want to upload the debug information files.

I have added the script to upload symbols as suggested [here](https://docs.sentry.io/platforms/javascript/cordova/) but I cannot find the debug symbols on Sentry.

When I run the following command from my terminal:
```bash
DWARF_DSYM_FOLDER_PATH=/Users/MY_NAME/Library/Developer/Xcode/DerivedData/Cood_Academy-hcfinwvmzxhhweavhjrolodeackx/Build/Products/Debug-iphoneos/
../../../node_modules/@sentry/cli/bin/sentry-cli upload-dif \"$DWARF_DSYM_FOLDER_PATH\" --org MY_ORG --log-level=debug --project MY_PROJECT
```

I get the following error: 
```bash
> Found 0 debug information files
> No debug information files found
> No new debug symbols to associate.
```

I do not understand why because I do have a .dsym file in the Debug-iphoneos folder.

- Cordova-ios version: 5.1.1
- sentry-cordova version: 0.12.3
- @sentry/cli version: 1.49.0

**Comment by expcapitaldev** [comment]
so, confirm issue with
DWARF_DSYM_FOLDER_PATH=XXX
node_modules/@sentry/cli/bin/sentry-cli upload-dif \"$DWARF_DSYM_FOLDER_PATH\"

> Found 0 debug information files
> No debug information files found
but files exists

similar issue for example:
cordova compile ios ... && node_modules/@sentry/cli/bin/sentry-cli upload-dif \"$DWARF_DSYM_FOLDER_PATH\"
> Found 0 debug information files
> No debug information files found
but DSYM files exists in the repo

**Comment by expcapitaldev** [comment]
resolved: see https://docs.sentry.io/platforms/javascript/guides/cordova/upload-debug/#uploading-using-xcode
`SENTRY_COMMAND="../../$SENTRY_CLI upload-dif \"$DWARF_DSYM_FOLDER_PATH\""`
double quotes wrong, should be https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/
`../node_modules/@sentry/cli/bin/sentry-cli upload-dif "$DWARF_DSYM_FOLDER_PATH"`
you can add additional log into sentry-cli bin file

**Comment by bruno-garcia** [comment]
Glad to hear it got sorted out.
