### ISSUE TITLE
Request: Update @sentry/* dependencies

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry-cordova#169]
Currently (version `0.17.0` of `sentry-cordova`), the dependencies are pinned at

```
    "@sentry/browser": "~5.6.3",
    "@sentry/core": "~5.6.2",
    "@sentry/minimal": "~5.6.1",
    "@sentry/types": "~5.6.1",
    "@sentry/utils": "~5.6.1",
```

Request: bump `@sentry/browser` (and friends) to at least `5.8.x`, to take advantage of the improvements in reporting of things like `CustomEvent`s.

**Comment by phal0r** [comment]
@HazAT 
Is there anything, we could do to help updating the dependencies?

**Comment by scic** [comment]
I would also appreciate an update of the dependencies to >= 5.27.*. i would like to use the improved performance tracking with the  additional tracing package.

**Comment by bruno-garcia** [comment]
We haven't been able to prioritize this, as work is being put on Capacitor:
https://github.com/getsentry/sentry-capacitor

But we could work in reviewing a PR if folks wanted to try updating it and opening a PR.
