### ISSUE TITLE
[Request] Env flag to disable sentry wizard

### ISSUE THREAD

**Issue by jskrzypek** [getsentry/sentry-cordova#17]
We're using a monorepo structure with all of our dependencies hoisted to the root, and a custom script to manage our cordova process. When the `before_plugin_install_uninstall.js` script runs for our ios apps, it runs `sentry-wizard` which calls `xcode.project(...)`. This will fail when it tries to fork it's parseJob script because of the hoisting.

Would it be possible to add an env variable flag to skip the sentry-wizard script like there is for `SENTRY_SKIP_AUTO_RELEASE`?

Thank you!

*****

fwiw, here's the error we get:
```sh
module.js:538
    throw err;
    ^

Error: Cannot find module '/Users/jskrzypek/dev/monorepo-project/packages/ionic-app/node_modules/xcode/lib/parseJob.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

The `xcode` lib is installed but at `~/dev/monorepo-project/node_modules/xcode` not `~/dev/monorepo-project/packages/ionic-app/node_modules/xcode`

**Comment by HazAT** [comment]
Added in `0.6.0`
