### ISSUE TITLE
enableNative and addBreadcrumb don't play well together

### ISSUE THREAD

**Issue by donald-hanson** [getsentry/sentry-cordova#172]
When I then try to add a breadcrumb, the breadcrumb is not sent to a subsequent error or message.

This is because the scopeListener registered when `enableNative` is set to `true` does the following:

```
...
this._nativeCall('addBreadcrumb', (internalScope as any)._breadcrumbs.pop()).catch(() => {
  // We do nothing since scope is handled and attached to the event.
  // This only applies to android.
});
...
```

The `_breadcrumbs.pop()` modifies the array in place so the newly added breadcrumb is dropped from the array and passed up to the native layer.

Calling `Sentry.captureException(...)` later does not include the previously added breadcrumb as it has been removed from the `Scope`.

**Comment by jennmueng** [comment]
We've fixed this in the latest release we just made: [1.0.0-rc.0](https://github.com/getsentry/sentry-cordova/releases/tag/v1.0.0-rc.0) where we removed that snippet of code and re-wrote the native layer scope sync.
