### ISSUE TITLE
Redundant information

### ISSUE THREAD

**Issue by Gemeapp** [getsentry/sentry-cordova#173]
- [x] Review the documentation: https://docs.sentry.io/
- [x] Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-javascript/releases
- [x] Provide a link to the affected event from your Sentry account

## Package + Version

- [x] `@sentry/browser`
- [ ] `@sentry/node`
- [ ] `raven-js`
- [ ] `raven-node` _(raven for node)_
- [x] Sentry_Cordova:

### Version:
```
sentry-cordova: 0.0.17
@sentry/browser 5.6.3 (Bundled) and installing 5.12.4 does not help
```

## Description

I would like a more condensed version of the breadcrums, and currently there is redundant information, when logging from the console 

This is an example where I just write "Sentry" in the console, and it then shows as
![image](https://user-images.githubusercontent.com/25880932/75347424-fcf2be80-58a0-11ea-8401-5d2853242519.png)

I haven't found any situations where there are information in extra, that is useful

I have considered disabling the default console-integration, and building a custom, but did not find the information needed to do that

Regards
Thorvald

**Comment by bruno-garcia** [comment]
You can try to modify the breadcrumbs on `beforeBreadcrumb` and remove some data
