### ISSUE TITLE
iOS Crash

### ISSUE THREAD

**Issue by Polm90** [getsentry/sentry-cordova#174]
I've created an empty project and installed only the sentr-cordova plugin.
However, even in this simple scenario, when I lunch the app on the iPad, the app crashes at startup with the following error.

yld: Library not loaded: @rpath/Sentry.framework/Sentry
  Referenced from: /private/var/containers/Bundle/Application/C8176A0D-9D77-4516-9D2F-F29FEE6AD1D7/AppSentrytest.app/AppSentrytest
  Reason: no suitable image found.  Did find:
 /private/var/containers/Bundle/Application/C8176A0D-9D77-4516-9D2F-F29FEE6AD1D7/AppSentrytest.app/Frameworks/Sentry.framework/Sentry: code signature invalid for '/private/var/containers/Bundle/Application/C8176A0D-9D77-4516-9D2F-F29FEE6AD1D7/AppSentrytest.app/Frameworks/Sentry.framework/Sentry'

 /private/var/containers/Bundle/Application/C8176A0D-9D77-4516-9D2F-F29FEE6AD1D7/AppSentrytest.app/Frameworks/Sentry.framework/Sentry: stat() failed with errno=25

I'm using sentry-cordova 0.17.0, cordova 9.0.0, xCode 11.3.1

**Comment by Polm90** [comment]
Issue still persists with xCode 11.4

**Comment by bruno-garcia** [comment]
Cordova 9 isnt' supported. #126 

But we're aiming an update with Cordova 10: #186

**Comment by jennmueng** [comment]
@Polm90 This looked to be an issue regarding our cocoa SDK on newer Xcode versions, if you bump to the latest release we just made (1.0.0-rc.0) it should be fixed. Closing this, please reopen if it persists.
