### ISSUE TITLE
error add plugin sentry-cordova on cordova 6

### ISSUE THREAD

**Issue by sebastiansinsin** [getsentry/sentry-cordova#175]
Hi @HazAT , I hope you're doing well. I need your help to solve this issues, I can't install plugin sentry-cordova on cordova 6 and cordova android 6. could you please help me?
Thanks! have a nice day!

Version which I installed with npm and add to package.json:
`"sentry-cordova": "^0.17.0",`

ionic info : 
`
Ionic:

   Ionic CLI          : 6.2.0 (C:\Program Files\nodejs\node_modules\@ionic\cli)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 6.5.0
   Cordova Platforms : android 6.4.0
   Cordova Plugins   : no whitelisted plugins (15 plugins total)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run (update available: 0.3.0)  : 0.2.9

System:

   NodeJS : v10.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 2.15.12
   OS     : Windows 10
`

Output Log :
`
Installing "sentry-cordova" for android
Subproject Path: CordovaLib
Cannot set property 'sentry-cordova' of undefined
`

**Comment by jennmueng** [comment]
We don't support Cordova 6, you would need at least Cordova 7 to use the SDK.
