### ISSUE TITLE
waiting for wizard to connect loading stuck

### ISSUE THREAD

**Issue by sebastiansinsin** [getsentry/sentry-cordova#181]
I've followed all the instruction on https://docs.sentry.io/platforms/javascript/guides/cordova/ionic/
and when I tried cordova plugin add sentry-cordova, it run sentry-wizard and stuck.

please help how to fix this. If I skip sentry-wizard, using set SENTRY_SKIP_WIZARD=true&&cordova plugin add sentry-cordova
and then I run the project on android ionic cordova run android -lc --emulator
I got an error 
[cordova] Sentry: sentry.properties does not exist in project root!

**Comment by vesper8** [comment]
Did you ever figure this out? I'm in the same position, sentry wizard just does nothing

**Comment by bitsandfoxes** [comment]
I'm not all too familiar with Cordova itself but the error message looks to me like the setup for Sentry CLI got skipped and the required properties file did not get created.
You could try creating it manually and see if this fixes it for you. The relevant docs can be found here: https://docs.sentry.io/product/cli/configuration/#properties-files
For examples look here: https://github.com/getsentry/examples/blob/e41adb27d31ed9015dc573f1a955b54b1b7f6d43/react-native/sentry.properties
