### ISSUE TITLE
How to capture native exceptions?

### ISSUE THREAD

**Issue by malwatte** [getsentry/sentry-cordova#182]
Is it possible to capture all native errors?

For example,
When I throw a null pointer exception from the native code in Android (in a Cordova plugin), 
`throw new NullPointerException();`
app gets restarted. But I cannot see any errors in Sentry dashboard.

I can see JavaScript and app crashes in Sentry dashboard.
Is capturing JavaScript and app crashes enough? Is my example above a invalid scenario in Cordova environment?

Thanks

**Comment by jennmueng** [comment]
Hmm it thrown native errors like that should be captured. Can you update to the latest version that we just released [1.0.0-rc.0](https://github.com/getsentry/sentry-cordova/releases/tag/v1.0.0-rc.0) and see if it works there?

**Comment by IhorKobylinskiy** [comment]
The same here. For native crash emulation I use [cordova-app-crash](https://github.com/AhsanAyaz/cordova-app-crash). It works fine for IOS but there are no reports for android. I also tried latest release.

**Comment by jennmueng** [comment]
@IhorKobylinskiy  Try the latest [1.0.0-rc.2](https://github.com/getsentry/sentry-cordova/releases/tag/v1.0.0-rc.2) and you can call `.nativeCrash()` from the JS side.

**Comment by bruno-garcia** [comment]
Sounds like it was resolved. Feel free to reopen otherwise
