### ISSUE TITLE
Missing command Error on cordova-browser

### ISSUE THREAD

**Issue by Polm90** [getsentry/sentry-cordova#184]
On cordova-browser it is raised a "Missing command Error" error and many console.log with this kind of messages "Error: exec proxy not found for :: Sentry :: addBreadcrumb"; however, the issues are correctly reported on the sentry portal

**Comment by stevebrowndotco** [comment]
I also get the same, my cordova browser production build is giving . There is more info in this comment that leads me to believe that the browser platform isn't supported by Sentry ... https://github.com/getsentry/sentry-cordova/issues/65#issuecomment-521449657

**Comment by Polm90** [comment]
> I also get the same, my cordova browser production build is giving the same logs. There is more info in this comment that leads me to believe that the browser platform isn't supported by Sentry ... [#65 (comment)](https://github.com/getsentry/sentry-cordova/issues/65#issuecomment-521449657)

Maybe is not fully supported... but it works! Even if the error I reported is raised...

**Comment by stevebrowndotco** [comment]
Ok, if it works then that's good. I was wondering do you know how to suppress these logs? As this happens in production..

**Comment by Polm90** [comment]
> Ok, if it works then that's good. I was wondering do you know how to suppress these logs? As this happens in production..

Unfortunately not... I was wondering the same...
