### ISSUE TITLE
Uninstalling sentry-cordova

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-cordova#19]
ref: https://github.com/getsentry/sentry/issues/7320

**Comment by HazAT** [comment]
I've added a dup package called `sentry-cordova` it should work now.
cc @schumannd @SpellChucker

**Comment by SpellChucker** [comment]
@HazAT We still get the issue when we do an `npm install`

```
npm ERR! addLocal Could not install /Users/samanta/dev/mobile-native/id90t-mobile-native/mobile/@sentry/cordova@~0.6.0
```
