### ISSUE TITLE
It's not clear from the docs which Sentry project should be created

### ISSUE THREAD

**Issue by yosikal** [getsentry/sentry-cordova#21]
I was not sure which project should be created on Sentry, I assume it's Android project for Android and iOS for iOS but it would been nice if the docs were clear about that.

**Comment by HazAT** [comment]
You are right about that and thank you for your feedback.
It really doesn't matter which kind of project you create, it is basically only a filter for which docs to show.
You can choose any project type.
I've created an issue on getsentry/sentry ref: https://github.com/getsentry/sentry/issues/7364
