### ISSUE TITLE
How do we ignore files for sourcemap upload? I am unable to build my release APK because of this and it is in fact breaking my Router

### ISSUE THREAD

**Issue by jbm1991** [getsentry/sentry-cordova#221]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
sentry-cordova@1.0.0

### Steps to Reproduce

1. I am trying to build my release APK, which appears to trigger a sourcemap upload of my application files to Sentry. The command I'm using to do this is `cordova build android --release ....`
2. There is a significant portion of my application files that I would like to exclude from this upload. These are libraries and other things that I have to use, but have no interest in error reporting on. My application is about 35MB in size when built, and about 33MB of these files are to be ignored - literally hundreds of thousands of files.
3. Because there are so many of these files and Sentry is attempting to upload them, my build process ultimately hangs until I manually kill it by restarting my computer - sending the keyboard interupt does not stop it.
4. Also, I assume it must be flooding my router with connection requests or something, as in the process of all of this it also takes out my router and I have to reboot that to get it to recover too. This is happening consistently when I run that command, much to the annoyance of everyone in my household.

### Expected Result

There is some way to stop the uploading of files to Sentry, either using an ignore file or CLI inputs or something.

### Actual Result

All the files are attempted to be uploaded and it crashes my Mac and Internet

**Comment by jbm1991** [comment]
I've discovered the parameter `SENTRY_SKIP_AUTO_RELEASE=true` in one of the other documentation sets (Ionic I think it was) which appears to solve my problem. Feel free to close this issue if this is the expected behaviour.

**Comment by jennmueng** [comment]
@jbm1991 Hmm you can use `SENTRY_SKIP_AUTO_RELEASE` for now, to fix this issue I think it makes sense to add a way to configure which files/folders to ignore when compiling source maps?

**Comment by jbm1991** [comment]
@jennmueng Yeah I think that would certainly be helpful, as it would be good to have the release management, rather than just blanket disabling it like I am now. Perhaps a new config line in the `sentry.properties` file? Then it would be compatible with all the many ways people build and compile their cordova (and other frameworks) apps?
