### ISSUE TITLE
setUser is not a function?

### ISSUE THREAD

**Issue by jbm1991** [getsentry/sentry-cordova#223]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-cordova@1.0.0 

### Steps to Reproduce

1. I'm trying to add User information as per https://docs.sentry.io/platforms/javascript/guides/cordova/enriching-events/identify-user/ however the setUser function does not exist

### Expected Result

I should be able to set the User

### Actual Result

I get a function undefined error

### Additional Notes/Comments

Whilst I have installed sentry-cordova@1.0.0, when I look at the SDK_VERSION property on Sentry in my App, the version reported is 0.17.0. Is that correct? Also, in the documentation I see the version is listed as 0.12.3 - am I using the wrong documentation?

**Comment by jennmueng** [comment]
@jbm1991 Looks like you're on the wrong version then, if SDK_VERSION is not `1.0.0`. I would do a re-install to make sure the correct version is present.

I will look into why our documentation still states the wrong version.

**Comment by jbm1991** [comment]
Hi @jennmueng thanks for confirm. Prior to making this ticket I've uninstalled and reinstalled multiple times, but it's still coming up with that version. I've tried installing with `cordova plugin add sentry-cordova@1.0.0` too and my package.json lists it correctly, however it still reports 0.17.0 unfortuantely

**Comment by jennmueng** [comment]
@jbm1991 Make sure that the version that Cordova copies over to your platforms folder `ios` `android` etc are the latest one.

**Comment by jbm1991** [comment]
Thanks @jennmueng it turns out my entire project had broken somehow, so I've reinstalled everything and it's working correctly now 😃
