### ISSUE TITLE
iOS build failing on MacOS with M1 chip

### ISSUE THREAD

**Issue by carlosen14** [getsentry/sentry-cordova#227]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

1. had my ptoject on a iMac i5, everything worked
2. moved to MBP m1 chip, did a clean npm i, ionic build --platform=ios , npx cap sync ios
3. npx cap open ios
3. tried to build on Simulator, but crashes. but building for a physical device does works!!

### Expected Result

to compile correctly on a simulator

### Actual Result

looks like some libs are missing for this specific arch
![image](https://user-images.githubusercontent.com/9368632/122689747-a3777700-d1ea-11eb-942e-a44eb0859a1c.png)

**Comment by carlosen14** [comment]
actually it worked, it compiled correctly.. now just have to adjust because the lib funcs appears to be different.

sorry, i did not looked into it, when i started using capacitor i guess the wasn't official support to it. but you have to know, the other lib (sentry-cordova) worked perfectly before moving into mac m1.

**Comment by carlosen14** [comment]
i'll keep in touch if after adjusting, something breaks! :)

**Comment by carlosen14** [comment]
actually, i guess something broke, because it is not recognizing SentryCapacitor obj, on that line it throws with error "SentryCapacitor.setUser is not a function", and actually it has value null and neither has other functions, but sentry.init does work.

![image](https://user-images.githubusercontent.com/9368632/122769088-db71cf00-d269-11eb-8653-952df4725641.png)

**Comment by jennmueng** [comment]
@carlosen14 This is because the native layer is not supported on iOS yet. You can init it like I suggested:

```js
Sentry.init({
  dsn: "___DSN___",
  enableNative: Capacitor.getPlatform() === "android"
})
```

**Comment by carlosen14** [comment]
> @carlosen14 This is because the native layer is not supported on iOS yet. You can init it like I suggested to disable it on iOS:
> 
> ```js
> Sentry.init({
>   dsn: "___DSN___",
>   enableNative: Capacitor.getPlatform() === "android"
> })
> ```

yes, i just tried and it is now working.. thanks for your time and help

**Comment by thoasty-dev** [comment]
Hey there, i got the same problem while building. What did you do to solve it?
