### ISSUE TITLE
How did you prepare your plugin for forks?

### ISSUE THREAD

**Issue by expcapitaldev** [getsentry/sentry-cordova#239]
I checked all your repos for CI : action-prepare-release/publish and etc. But how I can create my own fork and use  , because I see a lot of improvements in your issues.
Your repo is not cordova plugin, your repo only upload into npm all code.
Pls describe your opinion for your subscribers who pay money for your product, how we can use your plugin as a fork ?

**Comment by bruno-garcia** [comment]
You can use the plugin as a fork. You don't need to use that Publish workflow. Feel free to fork and modify/use/sell or whatever you want to do, the SDK is MIT licensed.
