### ISSUE TITLE
It's not clear from the docs if offline exception tracking is supported

### ISSUE THREAD

**Issue by yosikal** [getsentry/sentry-cordova#24]
I was assuming that when the device is offline the plugin will store expcetions and fire those to Sentry when the device is back online. Is that how it's working?

Anyway, when reporting exceptions when offline the following error appears on the console:
Uncaught (in promise) Error: Sentry error code: network unavailable(…)

**Comment by zabojad** [comment]
@yosikal so in the end is it caching temporarly offline exceptions?

**Comment by HazAT** [comment]
We support offline caching, we are in the process of setting up a new docs system, I will update the docs to reflect that accordingly.
