### ISSUE TITLE
update SDK see https://github.com/getsentry/sentry-cocoa

### ISSUE THREAD

**Issue by expcapitaldev** [getsentry/sentry-cordova#247]
We recommend you update your SDK from sentry.cocoa@v6.2.1 to sentry.cocoa@v7.5.2 (All sentry packages should be updated and their versions should match) - it is your warning for sentry cordova, pls check and update your sdk for cordova

**Comment by bruno-garcia** [comment]
This are pretty stable on the current version so for the time being we won't be making a version bump. This might change once we add "client outcomes".

**Comment by expcapitaldev** [comment]
@bruno-garcia  thank you,but how we can update sdk for cordova?
for android we can use this variable - https://github.com/getsentry/sentry-cordova/blob/main/plugin.xml#L45
but for ios ?

**Comment by expcapitaldev** [comment]
I created fork from your SDK https://github.com/getsentry/sentry-cordova/compare/main...expcapitaldev:main
