### ISSUE TITLE
Performance monitoring of the native integrations

### ISSUE THREAD

**Issue by jskrepnek** [getsentry/sentry-cordova#248]
Are there any obvious complications in the way before you can enable performance monitoring for the iOS / Android native integrations?  Are there plans to introduce this in the next version?

In the meantime, would you recommend against enabling it on Android via a `meta-data` element in AndroidManifest.xml?  I don't see a way to hack it in for iOS ATM.

**Comment by bruno-garcia** [comment]
I don't think it makes much sense to enable the native SDK performance monitoring feature. It won't give you insight inside the webview.
Performance for Cordova is basically following the guides for Browser JS. That said, we're not planning on actively 'adding support' for cordova (as in Vitals and other features) at this time. We would consider taking PRs though.
