### ISSUE TITLE
Cannot build for ios simulator with Apple M1 macbook

### ISSUE THREAD

**Issue by jamesmcb** [getsentry/sentry-cordova#252]
### Environment

Using sentry-cordova 1.0.0 for an ionic project with Xcode 13 on a macbook pro with an M1 Processor.

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.3
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 8.1.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 5.0.0, (and 16 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.5.0) : 0.2.9

System:

   ios-sim : 8.0.2
   NodeJS  : v16.13.2 (/usr/local/bin/node)
   npm     : 8.1.2
   OS      : macOS Monterey
   Xcode   : Xcode 13.2.1 Build version 13C100

### Steps to Reproduce

1. Run ionic cordova build ios

### Expected Result

It would build

### Actual Result

ld: warning: building for iOS Simulator, but linking in dylib built for iOS, 'Sentry.framework'
ld: warning: Could not find or use auto-linked framework 'Sentry'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SentryUser", referenced from:
      objc-class-ref in SentryCordova.o
  "_OBJC_CLASS_$_SentryBreadcrumb", referenced from:
      objc-class-ref in SentryCordova.o
  "_OBJC_CLASS_$_SentryEnvelope", referenced from:
      objc-class-ref in SentryCordova.o
  "_OBJC_CLASS_$_SentryEnvelopeItem", referenced from:
      objc-class-ref in SentryCordova.o
  "_OBJC_CLASS_$_SentryEnvelopeItemHeader", referenced from:
      objc-class-ref in SentryCordova.o
  "_OBJC_CLASS_$_SentryEnvelopeHeader", referenced from:
      objc-class-ref in SentryCordova.o
  "_OBJC_CLASS_$_SentrySdkInfo", referenced from:
      objc-class-ref in SentryCordova.o
  "_OBJC_CLASS_$_SentryId", referenced from:
      objc-class-ref in SentryCordova.o
  "_OBJC_CLASS_$_SentrySDK", referenced from:
      objc-class-ref in SentryCordova.o
  "_OBJC_CLASS_$_SentryOptions", referenced from:
      objc-class-ref in SentryCordova.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bruno-garcia** [comment]
What's the min version of Sentry Cocoa with support for M1 @philipphofmann ?

**Comment by philipphofmann** [comment]
If I remember correctly, we didn't have any significant issues with M1. Apple released the first M1 Macs in November 2020. Just to be safe I would pick [6.1.0](https://github.com/getsentry/sentry-cocoa/releases/tag/6.1.0) for the min version which we released in January 2021.

**Comment by philipphofmann** [comment]
From the error message I see that this is a problem with linking. As we are using Carthage to include sentry-cocoa, I think we should update to [7.2.0](https://github.com/getsentry/sentry-cocoa/releases/tag/7.2.0) in which we fixed an issue for Carthage with XCFrameworks.

**Comment by bruno-garcia** [comment]
@lucas-zimerman is this something you can help us with? We might need to bump the dependency and runs some tests

**Comment by lucas-zimerman** [comment]
running on iOS simulator seems to trigger this error even if you update sentry-cocoa, on the other hand, when targeting the device itself the error seems to be gone (M1)
