### ISSUE TITLE
Cordova-ios: no info.plist found

### ISSUE THREAD

**Issue by Polm90** [getsentry/sentry-cordova#269]
I'm using snetry-cordova 1.0.2 with cordova 11 and cordova-ios 6.2.0 (all latest versions).
When I try to build the ios ipa, i receive the following error:
There is no Info.plist found at '[cordova-project-path]/platforms/ios/[project-name]/Plugins/sentry-cordova/Sentry.xcframework/Info.plist'.

I'm using latest xCode version

**Comment by lucas-zimerman** [comment]
Hi Polm, a new version was released to solve this issue.
Let me know if you need anything elsel.

**Comment by Polm90** [comment]
With version 1.0.3 it works now.
Thank you.
