### ISSUE TITLE
warning about SDK version.

### ISSUE THREAD

**Issue by momodeveloper** [getsentry/sentry-cordova#272]
I am getting a warning when I click on native crash report in "my issues".
![image](https://user-images.githubusercontent.com/69371495/168559343-8d4541a0-fa8a-4d7c-b514-d54f0c812972.png)
it seems to me that sdk version 4.1.0 is quite old, and I wanted to know if an upgrade of the sdk version is coming soon ?

Thank you,

**Comment by bruno-garcia** [comment]
We plan to bump to the JS SDK version 7

**Comment by lucas-zimerman** [comment]
We plan to update the SDK once the update on React Native is completed, more info here: https://github.com/getsentry/sentry-react-native/pull/2250
