### ISSUE TITLE
Unable to install Capacitor plugin alongside latest angular plugin

### ISSUE THREAD

**Issue by ratnamyadav** [getsentry/sentry-cordova#277]
### Environment

Macbook Pro M1 Pro

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Angular 7.7.0, Capacitor 0.7.0

### Steps to Reproduce

1. Generate Angular 14 project or latest Ionic Project
2. npm i @sentry/capacitor

### Expected Result

Successfully install the plugin and use it in my app

### Actual Result

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @sentry/capacitor@0.7.0
npm ERR! Found: @sentry/angular@7.7.0
npm ERR! node_modules/@sentry/angular
npm ERR!   @sentry/angular@"^7.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @sentry/angular@"7.1.1" from @sentry/capacitor@0.7.0
npm ERR! node_modules/@sentry/capacitor
npm ERR!   @sentry/capacitor@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @sentry/angular@7.1.1
npm ERR! node_modules/@sentry/angular
npm ERR!   peerOptional @sentry/angular@"7.1.1" from @sentry/capacitor@0.7.0
npm ERR!   node_modules/@sentry/capacitor
npm ERR!     @sentry/capacitor@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/ratnamyadav/.npm/eresolve-report.txt for a full report.

**Comment by lucas-zimerman** [comment]
So you are having issues with Anguolar 14 with Sentry Capacitor? (not cordova).
If so, the issue may be resolved once a new version of the SDK with this PR https://github.com/getsentry/sentry-capacitor/pull/194 gets released.

**Comment by ratnamyadav** [comment]
Ok Thanks @lucas-zimerman
