### ISSUE TITLE
Source code was not found if JS file has relative path

### ISSUE THREAD

**Issue by expcapitaldev** [getsentry/sentry-cordova#284]
### Environment

that cordova plugin with version 1.0.3
Env:
**SENTRY_SKIP_AUTO_RELEASE= true
SENTRY_SKIP_WIZARD=true
sentry/cli": "2.5.0"**
I use sentry-cli with next steps: 
cd to application folder, where I will have next folders:
platforms/ <-- ios and android here
plugins/
www/

const iOSPath = [absolutePath]+platforms/ios/www
const androidPath = [absolutePath]+platforms/android/app/src/main/assets/www

sentry-cli releases new [name]@[version]
sentry-cli releases files [name]@[version] upload-sourcemaps --url-prefix=['test' or 'production' value here, because without that for android we will have buildVersion] [iOSPath or androidPath]
sentry-cli releases finalize [name]@[version]

I have real good path to files  after release:
![sentry3](https://user-images.githubusercontent.com/19390317/190086939-dd1a010d-374b-445f-996a-a707a523e2f0.png)
so, path created from www/ folder and it is expected case, all is ok 

all is good and I see all native and JS errors but I have next error if I have relative path to any JS files in stacktrace:
![sentry1](https://user-images.githubusercontent.com/19390317/190085411-30b99681-c13c-412e-981e-e3fc325a6d54.png)
we have good stacktrace, see:
![sentry2](https://user-images.githubusercontent.com/19390317/190085953-fb89f657-9f1d-40ec-9ae8-bfa26fff98ae.png)
olso, I checked stacktrace.frame I found bug in Sentry.
 Of course error in sentry-cordova/dist/js/sentry-cordova.bundle.js after build but see code here:
https://github.com/getsentry/sentry-cordova/blob/main/src/js/normalize.ts#L26
it is mean we will remove relative path to JS file and it is unexpected case, see:
![sentry5](https://user-images.githubusercontent.com/19390317/190089368-f0d529fb-18f9-47de-bb26-b5d593331a69.png)
 but after sentry release we wait relative path to file

olso we will not have real good stacktrace for cordova JS files and all other JS files too because they have relative path

![sentry7](https://user-images.githubusercontent.com/19390317/190090396-e01155bf-d3bb-4448-bc7c-5aff519ae8d4.png)

### Steps to Reproduce

create any error with stacktrace with JS files with relative path

### Expected Result

we do not need to see error in sentry with "Source code not found" for relative JS files

### Сonclusion

So, pls create **new hotfix** with that, because we can not change that if we add for example RewriteFramesIntegration too because we will have stacktrace frame after that changes (we will have filename after your function normalizeUrl, see https://github.com/getsentry/sentry-cordova/blob/main/src/js/normalize.ts#L26)
olso pls create unit test for that from your side
Thanks

**Comment by lucas-zimerman** [comment]
Hi, could you try running SentryCLI with the `--rewrite` parameter?

 example:
`sentry-cli releases -o myorg -p myproject files 1.0.8 upload-sourcemaps www/build --rewrite`

**Comment by expcapitaldev** [comment]
@lucas-zimerman thank you for your response, but:
1.  how rewrite parameter can help if rewrite parameter enabled by default (it is imformation from your documentation) ?
2. how simple app can help ? Do you think that event will be uploaded with relative  in sample app?
waiting response from your side, I am real want to help that plugin ti fix any issue and use your product.

**Comment by lucas-zimerman** [comment]
Hi expcapitaldev. 

2. a repro app helps a lot by helping us to understand where exactly the problem is, if it's something on the SDK itself, Sentry CLI or some user configuration issue.

**Comment by expcapitaldev** [comment]
@lucas-zimerman hi
did you check that case? You had to emulate any JS error in any JS file with relative path from root folder www.
We are waiting response from your side more than 8 days and as I understood you did not check that easy case from your side ?
We are using your product and I did not see any activity from your side, but you can spent for that case 5 minutes

**Comment by expcapitaldev** [comment]
@lucas-zimerman  hi, any updates?

**Comment by lucas-zimerman** [comment]
> @lucas-zimerman hi, any updates?

Sorry, I didn't have a chance to check this issue (if you would like to speed up this step you can contact the Sentry support)

So far this is what I have found:
I had issues with it but due to the dist not maching the sourcemaps
![image](https://user-images.githubusercontent.com/8229322/192785440-a82e4a69-5f75-4deb-b4e2-8e6fb18d5306.png)
With the correct dist set, it was able to find the files 
![image](https://user-images.githubusercontent.com/8229322/192785938-9926c3dd-43e6-41a9-863a-9b2f6ef1e4b2.png)
![image](https://user-images.githubusercontent.com/8229322/192786110-fd056fe3-959f-4ef4-aeba-4c3ddd2e2dde.png)

But in this case I used the default auto release integration, there's probably some additional steps for sentry cli to behave the same by removing the absolute path

**Comment by expcapitaldev** [comment]
@lucas-zimerman hi, thanks for feedback
as I understood you did not check steps which I provided, and I think you found issue , yep?

**Comment by lucas-zimerman** [comment]
> @lucas-zimerman hi, thanks for feedback as I understood you did not check steps which I provided, and I think you found issue , yep?

Correct, I used the Auto release feature (that uses Sentry CLI under the hood) to verify if it was broken or not (Otherwise I believe there would be more users complaining about it). Since the same is working, I'll verify what's going on the auto release in order to correctly upload the sourcemaps.

**Comment by expcapitaldev** [comment]
@lucas-zimerman  thanks a lot, waiting response from your side

**Comment by expcapitaldev** [comment]
@lucas-zimerman hi, did you have time to check it? Can you describe your next steps with issue ?

**Comment by expcapitaldev** [comment]
looks like Sentry team do not want to fix that critical bug for my opinion

**Comment by expcapitaldev** [comment]
any updates here?

**Comment by expcapitaldev** [comment]
we pay money for sentry
created bug with full description
shown line with bug
5 month without any hotfix/acitivity
the best SDK

**Comment by expcapitaldev** [comment]
ping

**Comment by elfiservice** [comment]
> https://github.com/getsentry/sentry-cordova/issues/284#issuecomment-1260888506

Hi @lucas-zimerman I would like some help to make this works in my Sentry project 
- my stack trace show all files with `app:///filename.js` in the begin of the file and my sourcemaps start with `~/filename.js` as well
- But in my issue Section my stack trace do not Link to SourceMap as you show in your images

**Comment by expcapitaldev** [comment]
nothing changed
