### ISSUE TITLE
Can't upload App to Apple App Store due to failed validation related to Sentry

### ISSUE THREAD

**Issue by yosikal** [getsentry/sentry-cordova#29]
See attached screenshot for validation failure details
![sentry](https://user-images.githubusercontent.com/5467649/36849574-13ed1124-1d6d-11e8-953a-2b7562dc1da1.jpg)

**Comment by HazAT** [comment]
Can you only build `Sentry.framework` for active architectures?
Also with what version Xcode are you building it?

**Comment by yosikal** [comment]
I need a little guidance on building only for active architectures. Where is the setting I should change?

I'm using Xcode 9.2

**Comment by HazAT** [comment]
I checked what's going on, and the framework we deliver is build with carthage which contains all possible architectures.

Please add the following `Run Script` to you Xcode `Build Phases`

```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

I will add this to our wizard so on a new setup this script will already be there.

**Comment by mrvipinkashyap** [comment]
Is this issue fixed in latest version?
I am using plugin version 0.8.5 in Ionic project and Xcode version Version 9.3 and on trying to submit build to app store I am several error similar to original issue reported in this thread. Please see attached screenshot. 
Please let me know if you need more information.

![screen shot 2018-04-11 at 8 48 23 pm](https://user-images.githubusercontent.com/6937626/38626534-6c3b0444-3dca-11e8-862b-f719e7249418.png)

**Comment by alexhisen** [comment]
Removing plugin and re-adding it seems to be sufficient to fix the above problem.

**Comment by glebmachine** [comment]
Re-installing of plugin don't fix the problem(

**Comment by harish50** [comment]
DEBUG [2019-03-16 00:46:08.58]: [Transporter]: DBG-X: parameter Errors = [ERROR ITMS-90087: "Unsupported Architectures. The executable for sollu.app/Frameworks/WebRTC.framework contains unsupported architectures '[x86_64, i386]'.", ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'sollu.app/Frameworks/WebRTC.framework/WebRTC' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.", ERROR ITMS-90125: "The binary is invalid. 
Can anyone please help me out?

**Comment by simonpeters** [comment]
Neither reinstall the platform or reinstalling the plugin fixes this for me.

**Comment by Polm90** [comment]
Still getting the issue

**Comment by gmotzespina** [comment]
Removing the embeded binary and rebuilding worked for me:

<img width="668" alt="Screen Shot 2019-08-08 at 08 57 55" src="https://user-images.githubusercontent.com/9021886/62709264-a4b6a680-b9ba-11e9-8b0d-ca08361d5ba8.png">

**Comment by ayyazzafar** [comment]
> I checked what's going on, and the framework we deliver is build with carthage which contains all possible architectures.
> 
> Please add the following `Run Script` to you Xcode `Build Phases`
> 
> ```
> APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"
> 
> # This script loops through the frameworks embedded in the application and
> # removes unused architectures.
> find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
> do
> FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
> FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
> echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"
> 
> EXTRACTED_ARCHS=()
> 
> for ARCH in $ARCHS
> do
> echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
> lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
> EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
> done
> 
> echo "Merging extracted architectures: ${ARCHS}"
> lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
> rm "${EXTRACTED_ARCHS[@]}"
> 
> echo "Replacing original executable with thinned version"
> rm "$FRAMEWORK_EXECUTABLE_PATH"
> mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"
> 
> done
> ```
> 
> I will add this to our wizard so on a new setup this script will already be there.

This solution worked for me. 
Thanks @HazAT

**Comment by mlegenhausen** [comment]
If you want to automate the process of adding this script to your project you can use the following cordova hook scripts in the `after_prepare` phase.

```js
const fs = require('fs');
const path = require('path');
const xcode = require('xcode');

const shellScript = `
APP_PATH="\${TARGET_BUILD_DIR}/\${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: \${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "\${EXTRACTED_ARCHS[@]}"
rm "\${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
`;

module.exports = context => {
  const projectDir = path.resolve(context.opts.projectRoot, 'platforms/ios')
  const dirContent = fs.readdirSync(projectDir)
  const matchingProjectFiles = dirContent.filter(filePath => /.*\.xcodeproj/gi.test(filePath));
  const projectPath = path.join(projectDir, matchingProjectFiles[0], 'project.pbxproj');

  const project = xcode.project(projectPath)

  project.parse(error => {
    if (error) {
      console.error('Failed to parse project', error);
      process.exit(1);
    }
    const options = {
      shellPath: '/bin/sh',
      shellScript,
      inputPaths: ['"$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"']
    };
    project.addBuildPhase(
      [],
      'PBXShellScriptBuildPhase',
      'Remove Unused Architectures',
      project.getFirstTarget().uuid,
      options
    );
    fs.writeFileSync(projectPath, project.writeSync());
  })
};

```

**Comment by neogenz** [comment]
Thanks @HazAT !

And tanks @mlegenhausen your script works perfectly.

Just for out team we put it in 
```json
"hooks": {
    "ionic:build:after": "./build-scripts/after_prepare.js"
},
```
of `package.json`. 
With Ionic 4, if we run your script in the `after_prepare` cordova hook (set in config.xml), architecture found by `lipo -info` after the final build still returning the bad architecture.

Thanks again you saved my day !

**Comment by leonelngande** [comment]
Thanks @mlegenhausen ! 

If you deploy for both ios and android, adding this script to after_prepare may break your android build process if you don't have the ios platform installed. Please note am using Ionic Angular.

It resolves the ios platform directory `const projectDir = path.resolve(context.opts.projectRoot, 'platforms/ios')`,  then reads it's content `const dirContent = fs.readdirSync(projectDir)`. This is where your build may break. 

To fix this, I've added a condition to stop the script if the directory does not exist.

```
    if ( !fs.existsSync(projectDir) ) {
        console.warn(
            `\nDirectory ${projectDir} does not exist, skipping removal of unwanted ios architectures.\n\n Did you run 'ionic cordova platform add ios'?`
        );
        return;
    }
```

Full script:
```
const fs = require('fs');
const path = require('path');
const xcode = require('xcode');

const shellScript = `
APP_PATH="\${TARGET_BUILD_DIR}/\${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: \${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "\${EXTRACTED_ARCHS[@]}"
rm "\${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
`;

module.exports = context => {
    const projectDir = path.resolve(context.opts.projectRoot, 'platforms/ios');
    if ( !fs.existsSync(projectDir) ) {
        console.warn(
            `\nDirectory ${projectDir} does not exist, skipping removal of unwanted ios architectures.\n\n Did you run 'ionic cordova platform add ios'?`
        );
        return;
    }
    const dirContent = fs.readdirSync(projectDir);
    const matchingProjectFiles = dirContent.filter(filePath => /.*\.xcodeproj/gi.test(filePath));
    const projectPath = path.join(projectDir, matchingProjectFiles[0], 'project.pbxproj');

    const project = xcode.project(projectPath);

    project.parse(error => {
        if (error) {
            console.error('Failed to parse project', error);
            process.exit(1);
        }
        const options = {
            shellPath: '/bin/sh',
            shellScript,
            inputPaths: ['"$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"']
        };
        project.addBuildPhase(
            [],
            'PBXShellScriptBuildPhase',
            'Remove Unused Architectures',
            project.getFirstTarget().uuid,
            options
        );
        fs.writeFileSync(projectPath, project.writeSync());
    })
};

```

**Comment by ericmulder** [comment]
I found that if I build the app using the --device flag Sentry only build for ARM. It actually makes sense because otherwise the app builds for the simulator which is i386. So using: `cordova build ios --release --device` I got the correct architectures to push a build to the app store.
