### ISSUE TITLE
Import Cocoa private hybrid SDK headers directly

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-cordova#291]
Hybrids SDKs, when using PrivateSentrySDKOnly class, will need to explicitly import <Sentry/PrivateSentrySDKOnly.h> alongside <Sentry/Sentry.h> starting with the next major release. The explicit import can already be added.

see https://github.com/getsentry/team-mobile/issues/66

**Comment by brustolin** [comment]
Cordova does not use "PrivateSentrySDKOnly" header yet. When we update Cordova to use it, we will do this.
