### ISSUE TITLE
sentry crash by [sentry_get_modules_list]

### ISSUE THREAD

**Issue by expcapitaldev** [getsentry/sentry-cordova#293]
### Environment

See https://github.com/getsentry/sentry-java/issues/1549
### Steps to Reproduce

See https://github.com/getsentry/sentry-java/issues/1549

### Expected Result

How we can update that if fixed only in here https://github.com/getsentry/sentry-java/pull/1591 ?

### Actual Result

Need to update sentry-native to 0.4.11+

**Comment by lucas-zimerman** [comment]
Hi and thanks for opening this issue!
Which version of Sentry Cordova are you using?
sentry-native should be 0.4.17 on the latest Cordova Release.

**Comment by expcapitaldev** [comment]
I use 1.0.3 , will update to the latest version
thanks a lot
