### ISSUE TITLE
can we use Session Replay  ?

### ISSUE THREAD

**Issue by expcapitaldev** [getsentry/sentry-cordova#300]
Hi!
Can you provide information, how we can use Session Replay https://docs.sentry.io/platforms/javascript/guides/angular/session-replay/ for cordova, beause it is webview and we can use it.
How we can update @sentry/browser for that in that repo to 7.X+ (https://www.npmjs.com/package/@sentry/browser)
 now I see we have 6.1.0 version https://github.com/getsentry/sentry-cordova/blob/main/package.json#L27

**Comment by expcapitaldev** [comment]
also I see it is enabled for capacitor https://github.com/getsentry/sentry-capacitor/pull/281

**Comment by lucas-zimerman** [comment]
Hi, the Replay feature is on hold while this issue is not sorted out: https://github.com/getsentry/sentry-capacitor/issues/318
once the issue is fixed, both Capacitor and Cordova will return the conclusion to support the Replay feature.
