### ISSUE TITLE
iOS release build error

### ISSUE THREAD

**Issue by gsanseverino** [getsentry/sentry-cordova#308]
Hello,

running release build for ios I'm getting this error:

```
SentryCordova.m:105:13: error: use of undeclared identifier 'options'; did you mean 'optind'?
         if (options[@'store']) {
             ^~~~~~~
             optind
             
SentryCordova.m:105:19: error: subscript requires size of interface 'NSNumber', which is not constant for this architecture and platform
        if (options[@'store']) {
                   ^~~~~~~~~
```

it's not happening for debug builds.

I'm using cordova 11, sentry-cordova 1.1.4

**Comment by gsanseverino** [comment]
shouldn't the `options` variable be `commandDictoinary` instead?

**Comment by marian-turchyn-oril** [comment]
@gsanseverino You made my day. Thx. Changing variable is working.

**Comment by awaken180-dev** [comment]
> 

How were you able to adjust this for the build?

**Comment by gsanseverino** [comment]
If you're using Ionic, the file is in the `platforms/ios/<ProjectName>/Plugins/sentry-cordova` folder

**Comment by gsanseverino** [comment]
If you change the file `platforms/ios/<ProjectName>/Plugins/sentry-cordova/SentryCordova.m` as explained in the first message, you can fix the issue. 

But I'm not using AppFlow, so if platform files are generated in that pipeline, you have to find a different solution.
