### ISSUE TITLE
IOS - Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by 9t96** [getsentry/sentry-cordova#311]
I get "Command PhaseScriptExecution failed with a nonzero exit code" on Strip unused archs phase when building on Xcode 14.3.

sentry-cordova: v1.1.5

I check this and its ok: https://docs.sentry.io/platforms/javascript/guides/cordova/troubleshooting/?original_referrer=https%3A%2F%2Fwww.npmjs.com%2F

I tried the following workaround but doesnt work for me:
_Originally posted by @RedEars in https://github.com/getsentry/sentry-cordova/issues/160#issuecomment-590592202_

Also tried replacing the script to the suggestes on this issue, but only work for installing on devices, keeps failing when tryuing to Archive for example: 
https://github.com/getsentry/sentry-cordova/issues/29#issuecomment-524251380
            
![image](https://user-images.githubusercontent.com/17754777/240646394-b3afb4c2-245b-431a-abf0-af9c04d516a5.png)

**Comment by 9t96** [comment]
The i could do about it? Thanks!

**Comment by pivalig** [comment]
Any updates?

**Comment by mayainle** [comment]
I have the same issue. Did you find a solution?

**Comment by igorsantos07** [comment]
This is happening to us as well...

Somewhere around the error output, it says this phase can be skipped by using `SENTRY_SKIP_FRAMEWORK_PATCH=true` before the build command you're running (which seems to have been originated at https://github.com/getsentry/sentry-wizard/issues/39). This did the trick for me, but I'm unsure if [this will cause trouble when we submit the app to iTunes Connect](https://docs.sentry.io/platforms/javascript/guides/cordova/troubleshooting/#error-when-submitting-to-app-store-connect).

Thus, also waiting for a final solution from maintainers.

**Comment by northkode** [comment]
same issue 
Sentry.framework/Sentry: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by igorsantos07** [comment]
Funny, that file indeed doesn't seem to exist after the build fails, but during it, it exists: adding `if [ -f "$FRAMEWORK_EXECUTABLE_PATH" ]` inside the for has no effect.

**Comment by northkode** [comment]
Have you been able to successfully archive a build?
My build works to run it, but i can't archive it to submit to apple.

**Comment by igorsantos07** [comment]
I don't have the _privileges_ in the company to do it, so I didn't reach this step hahah
However, given the links I posted in the previous comment, I guess it indeed wouldn't work. I think we'll need to sit and wait for some Sentry staff to find this issue. Maybe it's worth opening a support ticket mentioning this issue?

**Comment by lucas-zimerman** [comment]
sorry for the late response, I will take a look at it.

**Comment by 9t96** [comment]
> sorry for the late response, I will take a look at it.
> 
> @9t96 are you facing this issue on a Mac M1 or X86/X64?

No, im using Macbook Pro 2020 with Intel chip

**Comment by northkode** [comment]
I'm on m1 and this happens

**Comment by fbfdsouza** [comment]
any updates on here?

I don't if this can shed some light on the issue, but for me in relation to these two paths:

lipo -extract arm64 myproject_folder/platforms/ios/ProjectName/Plugins/sentry-cordova/Sentry.xcframework/ios-arm64/Sentry.framework/Sentry -output ~/Desktop/arm64_file

this I get the error:  must be a fat file when the -extract option is specified


lipo -extract arm64 myproject_folder/platforms/ios/ProjectName/Plugins/sentry-cordova/Sentry.xcframework/ios-arm64_x86_64-simulator/Sentry.framework/Sentry -output ~/Desktop/arm64_file

and this works.

but the second one seems to be related to the binaries that are meant to the simulator since the ios-arm64_x86_64-simulator and the first one for the device build I guess ios-arm64?

**Comment by lucas-zimerman** [comment]
Still checking it.

**Comment by mafikes** [comment]
The same problem.

**Comment by igorsantos07** [comment]
I was also facing this issue from an Intel Mac Mini 2020 (2019?).

**Comment by HappyTepid** [comment]
@lucas-zimerman do you have any update on this? I'm facing the possibility of having to remove Sentry from an iOS app just to be able to make releases

**Comment by lucas-zimerman** [comment]
> @lucas-zimerman do you have any update on this? I'm facing the possibility of having to remove Sentry from an iOS app just to be able to make releases

Does previous versions works for you? There's a fix being worked on it but lots of changes internally so it was being validated.

**Comment by gabn88** [comment]
@lucas-zimerman 

I changed the lines and the build did continue.

But now I have:

```
Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ujoouV/extracted/My.app/Frameworks/Sentry.framework : 0xe800801c (No code signature found.
```

**Comment by lucas-zimerman** [comment]
@gabn88 have you tried the latest release of Sentry Cordova?

**Comment by lucas-zimerman** [comment]
closing as completed, if the same persist, feel free to open a new issue.
