### ISSUE TITLE
Update android/iOS SDKs / sentry-javascript to latest

### ISSUE THREAD

**Issue by expcapitaldev** [getsentry/sentry-cordova#319]
Hi Sentry Team, can you please update native android/ios SDKs to the latest ?

- [x] Bump iOS SDK https://github.com/getsentry/sentry-cordova/pull/352
- [x] Bump Android SDK https://github.com/getsentry/sentry-cordova/pull/353
- [x] Bump JavaScriptSDK (V7) https://github.com/getsentry/sentry-cordova/pull/354

**Comment by expcapitaldev** [comment]
also we should use Legacy flow, see https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/legacy-uploading-methods/
 because Javascript version insdie sentry-cordova lower than 7.46.0

**Comment by expcapitaldev** [comment]
thanks for updating iOS SDK!
waiting JS and Android

**Comment by expcapitaldev** [comment]
hi Sentry team! Very important to update Sentry SDK to latest !

**Comment by wif70068** [comment]
Sentry and UXCam don't work together on Cordova right now. 
I suppose it's because Sentry Cordova is still missing https://github.com/getsentry/sentry-java/pull/2625 from Sentry Android 6.17.0. It's the exact same error which is only happening when both are installed, not when either one is installed without the other.

**Comment by expcapitaldev** [comment]
interesting, thanks for the information

**Comment by lucas-zimerman** [comment]
Thank you for pointing out user wif70068! 
There are some big changes on the Javascript side so we'll first bump the Capacitor SDK and once all the issues are sorted out we'll push the changes to Cordova too.

**Comment by expcapitaldev** [comment]
hi! any updates here ?

**Comment by lucas-zimerman** [comment]
sorry for the long delay, we will be back on updating the SDK shortly!

**Comment by lucas-zimerman** [comment]
I added some checkmarks to keep track of the PRs on the main issue
