### ISSUE TITLE
IOS - Where to set SENTRY_SKIP_DSYM_UPLOAD=true

### ISSUE THREAD

**Issue by 9t96** [getsentry/sentry-cordova#322]
### IOS

How to prevent dsym symbols upload on development?
Where do i need to set SENTRY_SKIP_DSYM_UPLOAD=true variable to work on build phase?

What version are you running? 1.2.0

### Steps to Reproduce

1. Build ios-cordova project
2. Run it on device

**Comment by lucas-zimerman** [comment]
Sorry for the late response

You can skip the dsym upload by setting the flag on your project settings.

You can access these settings by going to Project > Build Settings 

You can add the variable by clicking on the [+] icon on the top left and adding a user defined setting.
<img width="184" alt="image" src="https://github.com/getsentry/sentry-cordova/assets/8229322/f9904cb3-a517-4092-a3ee-f4c9eba6437c">


<img width="363" alt="image" src="https://github.com/getsentry/sentry-cordova/assets/8229322/feedefc0-eb0a-49ee-ab71-b7c838f28fa1">

**Comment by 9t96** [comment]
> Sorry for the late response
> 
> You can skip the dsym upload by setting the flag on your project settings.
> 
> You can access these settings by going to Project > Build Settings
> 
> You can add the variable by clicking on the [+] icon on the top left and adding a user defined setting. <img alt="image" width="184" src="https://private-user-images.githubusercontent.com/8229322/291311198-f9904cb3-a517-4092-a3ee-f4c9eba6437c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDYyNzQsIm5iZiI6MTcwMzAwNTk3NCwicGF0aCI6Ii84MjI5MzIyLzI5MTMxMTE5OC1mOTkwNGNiMy1hNTE3LTQwOTItYTNlZS1mNGM5ZWJhNjQzN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTcxMjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTEzZTBhMzk1ZDIzMzdmY2I0MDNkOWYzOWZiZThkM2M5ZGUzMTUxOGNmZmY2OTBkZjg4MjRkNWJjYTFkNDVkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xrWBS6j2WZ9d8zv8CUKkScGvR7CJqkbIv8jd2GHz8GM">
> 
> <img alt="image" width="363" src="https://private-user-images.githubusercontent.com/8229322/291310624-feedefc0-eb0a-49ee-ab71-b7c838f28fa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDYyNzQsIm5iZiI6MTcwMzAwNTk3NCwicGF0aCI6Ii84MjI5MzIyLzI5MTMxMDYyNC1mZWVkZWZjMC1lYjBhLTQ5ZWUtYWI3MS1iN2M4MzhmMjhmYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTcxMjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQyNzgyMTZlZjIyMDRkNTZmZWIwOGZiNTg3MDVmOWY3NTM5YTNmNmU0NmY3ZWFlYjk5MjVhNGRmNGQ0N2M1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OibPE3ArsckRrd80TbsLK1xZHaNllncxd3FE5--uAc4">

Thanks! That solved my problem
