### ISSUE TITLE
Cannot read property ‘_globalOptions’ of undefined

### ISSUE THREAD

**Issue by jpgilchrist** [getsentry/sentry-cordova#33]
Trying to get sentry-cordova setup, but I'm hitting issues. Here's my code to initialize 

```javascript
const _initSentry = () => {
    window.initLogs.push(`${new Date()}: Sentry Initialization Start`);
    const Sentry = cordova.require('sentry-cordova.SentryCordovaBundle').default;
    const SentryBrowser = cordova.require('sentry-cordova.SentryCordovaBundle').SentryBrowser;
    const SentryCordova = cordova.require('sentry-cordova.SentryCordovaBundle').SentryCordova;

    Sentry.create(`${sentryUrl}`)
        .use(SentryCordova, {sentryBrowser: SentryBrowser})
        .install()
        .then((client) => {
            window.initLogs.push(`${new Date()}: Sentry Initialization Success`);
            client.captureException(new Error('hello sentry'));
        })
        .catch((e) => {
            window.initLogs.push(`${new Date()}: Sentry Initialization Failure - ${e.message}`);
        });
};
```

which is triggered in 
```javascript
document.addEventListener('deviceready', () => {
    ...
    _initSentry();
    ...
});
```

After debugging the code I find myself in SentryCordova.bundle.js:4185 with `SentryCordova.prototype.nativeCall` entering it's catch method with `e === 'not implemented'` evaluating to true.

I have no idea where to go from here. Hopefully I'm just doing something wrong. If you need more information, please ask :)

**Comment by HazAT** [comment]
Hey, I will look into this today, that's definitely a bug.

**Comment by jpgilchrist** [comment]
@HazAT I know you're looking into it, but I was just wondering if you had an estimate of time/work to fix it?

**Comment by HazAT** [comment]
@jpgilchrist Sorry for not replying earlier. 
I quickly looked into the issue and couldn't find the reason for reporting this error.
I am currently working on a rewrite: https://github.com/getsentry/sentry-cordova/pull/34
hopefully, this will fix it.

**Comment by jpgilchrist** [comment]
@HazAT okay thanks for the update. Do you have a timeframe for #34?

**Comment by HazAT** [comment]
@jpgilchrist We are in the middle of another rewrite 😓 
Sorry for that, I am pretty confident it should be done by the end of the week.
