### ISSUE TITLE
Session Replay for Ionic

### ISSUE THREAD

**Issue by ab-cap** [getsentry/sentry-cordova#340]
Hello.

Could you provide information whether I integrate Session Replay into my Ionic Cordova app?
I couldn't find any information about that, just for Capacitor.

I found [comment](https://github.com/getsentry/sentry-cordova/issues/300#issuecomment-1446212156) in a similar thread and as I see the issue in this comment is resolved but there is no further information.

Thanks in advance.

**Comment by lucas-zimerman** [comment]
Hi and thanks for opening this issue!
We will add support for the next release!

**Comment by ab-cap** [comment]
@lucas-zimerman 
Hello, I really appreciate for the answer and looking forward to the release :)

**Comment by lucas-zimerman** [comment]
An update: Replay was added on the latest release.

**Comment by ab-cap** [comment]
@lucas-zimerman great news, thanks a lot for notice
