### ISSUE TITLE
[Question] how use enableCaptureFailedRequests options ?

### ISSUE THREAD

**Issue by expcapitaldev** [getsentry/sentry-cordova#343]
My question related to https://docs.sentry.io/platforms/apple/guides/ios/configuration/http-client-errors/#customize-or-drop-the-error-event , how I can disable reporting in Sentry SDK HTTP errors ?

**Comment by expcapitaldev** [comment]
hi Sentry team, 
any updates ?

**Comment by lucas-zimerman** [comment]
Hi @expcapitaldev  and sorry for the late response.
You can set it from the JavaScript code as shown on this example:
```javascript
function onDeviceReady() {
  var Sentry = cordova.require("sentry-cordova.Sentry");
  Sentry.init({
    dsn: 'YOUR_DSN',
    ...
    enableCaptureFailedRequests: false,
  });
```

please let me know if you have any more questions.

**Comment by expcapitaldev** [comment]
hi Culas, thanks for feedback, but we have some lint errors, looks like will be better to upate d.ts file
`
Object literal may only specify known properties, and enableCaptureFailedRequests does not exist in type Partial<CordovaOptions>`
but I think issue resolved and we have solution for it

**Comment by lucas-zimerman** [comment]
Yeah it is not wrong, you can use `// @ts-ignore` above it for the time being while the options doesnt bundle `enableCaptureFailedRequests`
