### ISSUE TITLE
Error "Invalid DSN" with Android

### ISSUE THREAD

**Issue by ThomasKientz** [getsentry/sentry-cordova#35]
Hi, 

Plugin works great with iOS but I got this issue in the console of my Android device 

`Uncaught exception from plugin io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[secret key]'`

My DSN is set like that in `app.component.ts`

```
this.platform.ready().then(() => {
      Sentry.create({
        dsn: "myDSN"
      });
});
```

Environment :

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v9.5.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 
```

**Comment by HazAT** [comment]
Can you use the "private" DSN for now, we want to get rid of it because it's not actually private but it should fix your problem.
You should find it below your public DSN in the Sentry backend.
