### ISSUE TITLE
NullPointerException in LifecycleRegistry.removeObserver

### ISSUE THREAD

**Issue by kevinswartz** [getsentry/sentry-cordova#357]
### Environment

Cordova CLI: 11.1.0
cordova-android: 13.0.0
sentry-cordova: 1.2.0, and also 1.4.0

### Steps to Reproduce

We stared receiving crash reports in sentry and within google play about a crash in our app when using sentry-cordova 1.2.0.  We updated to 1.4.0 to fix, but we appear to have the same issue.  I've attached some screenshots to describe the problem further.  In the screenshots, v1.30.7 uses sentry-cordova 1.2.0, and v1.30.8 uses sentry-cordova 1.4.0.  I cannot reproduce anything locally.

This issue looks similar to this: https://github.com/getsentry/sentry-java/issues/2675

It appears from the sentry-cordova release notes for sentry-cordova 1.4.0 that it is using v7.14.0 of the android sdk, and this supposedly has the fix.  However I still see the same message in google play, so something isn't quite right here.

### Expected Result

I would expect that updating to cordova-android would fix the problem as described by the google play error report.

### Actual Result

![Image](https://github.com/user-attachments/assets/845469e8-7c3c-483e-ad36-dc27a86e78ec)
![Image](https://github.com/user-attachments/assets/2b7f06ff-125c-4195-8402-8a6314d29360)
![Image](https://github.com/user-attachments/assets/a4d884d9-f8fd-4d3e-ba70-d5bc6f9dbc00)

**Comment by lucas-zimerman** [comment]
Hi and thank you for opening this issue! 
This issue will be fixed shortly on the next release.

**Comment by lucas-zimerman** [comment]
> Thank you so much for your help! Do you have an estimate of when this release will be out so we can communicate that with our customers?

It should be released this week

**Comment by kevinswartz** [comment]
Hi guys, any word on a release for this?  Thanks for your help!

**Comment by lucas-zimerman** [comment]
Hi, it got released yesterday, please let us know if it's all good on your side

**Comment by kevinswartz** [comment]
Thanks for your help here.  I discovered the problem was actually on our end.  We updated our package.json by just incrementing the sentry-cordova version numbers and reinstalling platforms/plugins, which was not updating the `SENTRY_ANDROID_SDK_VERSION` variable.  After doing a full `ionic cordova plugin rm sentry-cordova && ionic cordova plugin add sentry-cordova` things are updated correctly.
