### ISSUE TITLE
Upload Sentry-cli uploading datas on every "cordova prepare"

### ISSUE THREAD

**Issue by ThomasKientz** [getsentry/sentry-cordova#36]
When running `$ cordova prepare`, I have to wait a few minutes that Sentry cli finishes uploading datas. Very annoying !

<img width="1440" alt="capture d ecran 2018-03-27 a 13 42 21" src="https://user-images.githubusercontent.com/10157845/37965347-134c21c6-31c5-11e8-9831-54806d04b9eb.png">

**Comment by HazAT** [comment]
You can add `SENTRY_SKIP_AUTO_RELEASE=true` in from of `cordova prepare` then the upload should not happen all the time.
Keep in mind in order for Sentry to provide symbolicated stacktraces we need this step to run (upload sourcemaps).

**Comment by kodeine** [comment]
is there a way to have this value set in package.json or somewhere there's more control programmatically?
