### ISSUE TITLE
Ionic missing sourcemap in prod mode

### ISSUE THREAD

**Issue by alexbonhomme** [getsentry/sentry-cordova#4]
Hey,

There is an issue during compilation with `--prod` flag on ionic. As Ionic do not include sourcemaps in production release, sentry-wizard try to access to missing files. 

```
Error: ENOENT: no such file or directory, open '/Users/alex/Development/1_ALEX-ET-MANON/lab/Vliller/vliller/platforms/android/assets/www/build/main.js.map'
```

Could we switch off the sourcemap upload ? With a flag for example ?

Thanks!

**Comment by HazAT** [comment]
Hey, I am looking into this.
Will release a new version as soon as I fixed both issues.
Thank you for your feedback 👍

**Comment by HazAT** [comment]
Hey so it was mainly a docs issue, we need the sourcemaps in order to symbolicate the crashes.
see: https://docs.sentry.io/clients/cordova/ionic/

You have to add this
```
"config": {
    "ionic_generate_source_map": "true"
}
``` 
to you `package.json`.

**Comment by kirillgroshkov** [comment]
Next step is to fix `//# sourceMappingUrl`, fix is available here: https://github.com/ionic-team/ionic-app-scripts/issues/1235
