### ISSUE TITLE
Native call errors are swallowed

### ISSUE THREAD

**Issue by mikejpeters** [getsentry/sentry-cordova#40]
Any errors calling native code are swallowed:

https://github.com/getsentry/sentry-cordova/blob/cf004f539306b8cf1e12155baad18a128f05ffda/src/js/backend.ts#L89-L97

There should probably be an `else` statement to handle the error in case it's not 'not implemented' or 'Cordova.exec not available'. I guess the error should be re-thrown, but that will still result in an uncaught promise error during `CordovaBackend#install()` .

I think it would be nice to have `Sentry.create()` return a promise that can be rejected in case of an error. However I'm not sure how to go about creating a pull request to do that. I have an idea how to improve `CordovaBackend` but for it to be useful it would require changing the `Backend` interface and the `createAndBind` method, both part of `@sentry/core`.

```patch
--- src/js/backend.ts	(revision cf004f539306b8cf1e12155baad18a128f05ffda)
+++ src/js/backend.ts	(date 1522181912717)
@@ -35,15 +35,19 @@
   /**
    * @inheritDoc
    */
-  public install(): boolean {
-    this.browserBackend.install();
+  public install(): Promise<void> {
+    return new Promise((resolve, reject) => {
+      this.browserBackend.install();
 
-    if (this.isCordova()) {
-      this.deviceReadyCallback = () => this.runNativeInstall();
-      document.addEventListener('deviceready', this.deviceReadyCallback);
-    }
-
-    return true;
+      if (this.isCordova()) {
+        this.deviceReadyCallback = () => {
+          this.runNativeInstall().then(resolve).catch(reject);
+        };
+        document.addEventListener('deviceready', this.deviceReadyCallback);
+      } else {
+        resolve();
+      }
+    });
   }
 
   /**
@@ -93,18 +97,22 @@
       ) {
         // This is our fallback to the browser implementation
         return (this.browserBackend as any)[action](...args);
+      } else {
+        throw e;
       }
     });
   }
 
-  private runNativeInstall(): void {
+  private runNativeInstall(): Promise<any> {
     document.removeEventListener('deviceready', this.deviceReadyCallback);
     if (this.frontend.getDSN()) {
-      this.nativeCall(
+      return this.nativeCall(
         'install',
         this.frontend.getDSN()!.toString(),
         this.frontend.getOptions(),
       );
+    } else {
+      return Promise.reject(new Error('DSN not configured'));
     }
   }
 

 ```

**Comment by HazAT** [comment]
We use `console.error` to not silently fail probably not the best solution but it should do for now since the "this should actually never happen" 🙄😅
