### ISSUE TITLE
Uncaught SyntaxError on Android devices

### ISSUE THREAD

**Issue by eldadfux** [getsentry/sentry-cordova#43]
Just tried to setup the Cordova plugin for the first time, on iOS  everything seems to work great and I can see the errors on my Sentry console. With my Android devices I get this errors on developer tools console.

`plugins/sentry-cordova/dist/js/sentry-cordova.bundle.min.js:2 Uncaught SyntaxError: missing ) after argument list
2018-04-01 10:51:23.672 cordova.js:1461 Uncaught Error: Module sentry-cordova.Sentry does not exist.`

Is there anything I am missing? the installation instructions were pretty straightforward.

**Comment by HazAT** [comment]
Hey, please upgrade to latest version `0.11.0` and check if this error still exists.
Warning there are some breaking changes, check the changelog https://github.com/getsentry/sentry-cordova/releases/tag/v0.11.0
