### ISSUE TITLE
Sentry.captureException Error (iOS)

### ISSUE THREAD

**Issue by jpgilchrist** [getsentry/sentry-cordova#44]
I had opened a similar issue for Android and that's now resolved, but iOS is still having issues. 

```javascript
const _initSentry = () => {
    window.Sentry = cordova.require('sentry-cordova.Sentry');
    window.Sentry.create({
        dsn: 'https://...@sentry.io/303006',
        release: APP_VERSION // eslint-disable-line
    });
    window.Sentry.captureException(new Error('Sentry Initialized'));
};
```

ouputs

```
TypeError: n.sent is not a function. (In 'n.sent()', 'n.sent' is undefined) (anonymous function) — sentry-cordova.bundle.min.js:327 d — app.js:14 (anonymous function) — app.js:12:427 g — app.js:12:185 promiseReactionJob
```

**Comment by jpgilchrist** [comment]
If you need anymore information, just let me know.

**Comment by HazAT** [comment]
I wasn't able to reproduce it, can you try to update to the latest version and try again?
Keep in mind we renamed `create` to `init`.

**Comment by jpgilchrist** [comment]
@HazAT I updated to the latest and ran it with the correct code and it's still happening. In fact it's going in an infinite loop since it itself is an unhandled error that keeps trying to report itself. Would cordova or platform versions matter? 

```javascript
const _initSentry = () => {
    window.Sentry = cordova.require('sentry-cordova.Sentry');
    window.Sentry.init({
        dsn: 'https://275cd48f1a9c4feda43f7dd9d9f9c298@sentry.io/303006',
        release: APP_VERSION // eslint-disable-line
    });
    window.Sentry.addBreadcrumb({message: 'sentry initialized breadcrumb'});
    window.Sentry.captureMessage('Sentry Initialized');
    try {
        throw new Error('Sentry Initialized Test Exception');
    } catch (e) {
        window.Sentry.captureException(e);
    }
};
```

**Comment by HazAT** [comment]
What's strange about this bug is, that we don't have a function called `sent` in our codebase.
Also not sure what `promiseReactionJob` this should mean.

**Comment by jpgilchrist** [comment]
That is peculiar.

**Comment by jpgilchrist** [comment]
@HazAT unless I'm not understanding something `sentry-cordova.bundle.js:584` has the following:

```javascript
    FrontendBase.prototype.sendEvent = function (event, scope) {
        return __awaiter(this, void 0, void 0, function () {
            var prepared, _a, shouldSend, beforeSend, afterSend, finalEvent, code, status;
            return __generator(this, function (_b) {
                switch (_b.label) {
                    case 0:
                        if (!this.isEnabled()) {
                            return [2 /*return*/, status_1$1.SendStatus.Skipped];
                        }
                        return [4 /*yield*/, this.prepareEvent(event, scope)];
                    case 1:
                        prepared = _b.sent();
                        _a = this.getOptions(), shouldSend = _a.shouldSend, beforeSend = _a.beforeSend, afterSend = _a.afterSend;
                        if (shouldSend && !shouldSend(prepared)) {
                            return [2 /*return*/, status_1$1.SendStatus.Skipped];
                        }
                        finalEvent = beforeSend ? beforeSend(prepared) : prepared;
                        return [4 /*yield*/, this.getBackend().sendEvent(finalEvent)];
                    case 2:
                        code = _b.sent();
                        status = status_1$1.SendStatus.fromHttpCode(code);
                        if (status === status_1$1.SendStatus.RateLimit) {
                            // TODO: Handle rate limits and maintain a queue. For now, we require SDK
                            // implementors to override this method and handle it themselves.
                        }
                        if (afterSend) {
                            afterSend(finalEvent, status);
                        }
                        return [2 /*return*/, status];
                }
            });
        });
    };
```

**Comment by jpgilchrist** [comment]
also of note `BrowserBackend.prototype.sendEvent` does return a `Promise`

```javascript
    BrowserBackend.prototype.sendEvent = function (event) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                return [2 /*return*/, new Promise(function (resolve) {
                        sendRavenEvent(prepareEventForRaven(event), function (error) {
                            // TODO: Check the response status code
                            resolve(error ? 500 : 200);
                        });
                    })];
            });
        });
    };
```

**Comment by HazAT** [comment]
You are right, sorry that I missed that.
I am still puzzled what's going on though.
The `sent` function comes from from the `__generator` which is created by the typescript compilation.
Can you add a breakpoint in your Xcode project and see if you reach the `sendEvent` function in `plugins/SentryCordova.m`?
It should actually never hit the `BrowserBackend` at least not on iOS.

**Comment by jpgilchrist** [comment]
@HazAT I'm actually not able to as my debugger crashes with the infinite looping. I tried to throw it in a try/catch to stop the infinite loop, but it didn't work. Any suggestions?

**Comment by HazAT** [comment]
Hey, can you please upgrade to `0.10.0` and try again?

**Comment by jpgilchrist** [comment]
Yes. I will try that...

**Comment by jpgilchrist** [comment]
@HazAT I tried with 0.10.2 and I'm getting the same issues.

**Comment by HazAT** [comment]
Hey, please upgrade to latest version `0.11.0` and check if this error still exists.
Warning there are some breaking changes, check the changelog https://github.com/getsentry/sentry-cordova/releases/tag/v0.11.0

**Comment by jpgilchrist** [comment]
@HazAT I just got some error, this time in Android. I ran it on iOS as well and it's definitely not working. However, I'm unable to debug any part of the iOS as Safari's dev tools crash every time. 

https://sentry.io/share/issue/7ce31bc3a331418580fd804ca1af0779/

**Comment by HazAT** [comment]
@jpgilchrist I am really sorry, I am not able to reproduce your issue.
Is your project open source? Can you send me a minimal reproducible example?
If I put exactly your code into a clean new Cordova application it works.

**Comment by jpgilchrist** [comment]
@HazAT no unfortunately and we have so much legacy "stuff" in there it's hard to reproduce.
