### ISSUE TITLE
Contexts don't seem to work with Ionic

### ISSUE THREAD

**Issue by SpellChucker** [getsentry/sentry-cordova#46]
Trying to send contexts like so:

```
import * as Sentry from 'sentry-cordova'

...

Sentry.setUserContext(...)
Sentry.setTagsContext(...)
```

~I don't see any extra information in my events nor on the HTTP request.~

Okay, I see what I did wrong here. I am trying to turn off sentry at runtime by running `Sentry.create({ dsn: '...' })` but doing so gets rid of the contexts. Is there a way to disable sentry runtime? Like set the DSN to a blank string? I don't see any function on the Sentry object to do this...

**Comment by HazAT** [comment]
Sorry, we are still in the process of documenting everything properly since we are using the new core architecture internally.
Please try to set `enabled: false` as an option.

**Comment by SpellChucker** [comment]
So set `enabled: false` as an option to the `create` method? I think this doesn't solve the issue because it's re-creating the Sentry setup therefore removing the contexts. I'll test this out though.

**Comment by HazAT** [comment]
Oh, sorry, I probably misunderstood your question.
Have you tried not to call `create` at all if you don't want to send events?
Because in general, all the calls should work even without calling `create`.

**Comment by SpellChucker** [comment]
Yeah. But my problem is this:

We have an in-house service API that we call to check if we want sentry logs enabled. This service can be called at any time and can either be `true` (yes, we want sentry logging), or `false` (no, we don't want sentry logging).

Now when our app starts up, we create the sentry instance using the `Sentry.create(...)` method. If, at any point in the future, we want to turn off sentry logs (by turning the flag mentioned above to `false`), it would be nice to just have some sort of method on the existing sentry object to disable logs. Similar to how we set contexts (`Sentry.setEnabled(false)` would be nice).

The way I'm working around this is by calling `Sentry.create(...)` with an empty `dsn` value if the service says to disable sentry. Doing this will remove all existing contexts. Otherwise, if the service says to enable sentry, I re-create the sentry instance by calling `Sentry.create(...)` with our valid DSN and by re-applying all the contexts.

**Comment by HazAT** [comment]
OK got it, so what I would instead is.
There is an option called `shouldSend`
```
/**
   * A callback invoked during event submission, allowing to cancel the process.
   * If unspecified, all events will be sent to Sentry.
   *
   * This function is called for both error and message events before all other
   * callbacks. Note that the SDK might perform other actions after calling this
   * function. Use {@link Options.beforeSend} for notifications on events
   * instead.
   *
   * @param event The error or message event generated by the SDK.
   * @returns True if the event should be sent, false otherwise.
   */
  shouldSend?(event: SentryEvent): boolean;
```

Sentry.create({
   dsn: 'Correct dsn,
   shouldSend: () => {
       return true; // return false to not send it.
   }
});

```
You can return a global constant and set it depending on the result of your request.
Hope this helps.

**Comment by SpellChucker** [comment]
Oh very interesting, that should help a lot! Thank you! I'll close the issue.
