### ISSUE TITLE
"t is not a function" 

### ISSUE THREAD

**Issue by zabojad** [getsentry/sentry-cordova#51]
I'm having this when calling `Sentry.captureMessage("...")`:
```
Uncaught (in promise) TypeError: t is not a function
    at sentry-cordova.bundle.min.js:2
```

<img width="1329" alt="screen shot 2018-04-30 at 16 21 16" src="https://user-images.githubusercontent.com/1238030/39431986-aa752952-4c92-11e8-8e21-8c415268af22.png">

<img width="890" alt="screen shot 2018-04-30 at 16 22 04" src="https://user-images.githubusercontent.com/1238030/39431995-add4dfac-4c92-11e8-8b2e-9dad57104c63.png">

Why?

**Comment by zabojad** [comment]
Happens both with cordova-ios and cordova-android:

<img width="1002" alt="screen shot 2018-04-30 at 16 54 43" src="https://user-images.githubusercontent.com/1238030/39433855-40f2cb9c-4c97-11e8-8573-ba233d339266.png">

**Comment by zabojad** [comment]
anything new on this one ?

**Comment by HazAT** [comment]
Can you please update to the latest version and try again? (`0.10.0`)

**Comment by HazAT** [comment]
Hey, please upgrade to latest version `0.11.0` and check if this error still exists.
Warning there are some breaking changes, check the changelog https://github.com/getsentry/sentry-cordova/releases/tag/v0.11.0
