### ISSUE TITLE
Error when uploading archive to ITunes connect

### ISSUE THREAD

**Issue by zabojad** [getsentry/sentry-cordova#52]
<img width="740" alt="screen shot 2018-04-30 at 17 17 16" src="https://user-images.githubusercontent.com/1238030/39435039-9e5318d4-4c9a-11e8-92a0-6e50700b4ce8.png">

**Comment by zabojad** [comment]
OK, thanks! Maybe a note about that in the README would be useful?

**Comment by AlejandroSilva** [comment]
@alexhisen Hi! with Ionic I have the same problem. Trying to re-adding the plugin don't fix the issue:
```
cordova plugin rm sentry-cordova 
cordova plugin add sentry-cordova 
```
The problems seems to be the architectures in the Sentry.framework package, as is seen at the moment of making the Archive:

<img width="742" alt="captura de pantalla 2018-05-25 18 42 01" src="https://user-images.githubusercontent.com/569481/40568894-7e138fda-604b-11e8-942f-e849388c545c.png">

Theres any way to make it work with iOS? i really like Sentry but if it don't work with iOS I will have to remove it completely from this and other projects in our organization and find an alternative :/

**Comment by HazAT** [comment]
@AlejandroSilva Have you checked the docs?
Wizard usually installs another run script in your Xcode project which strips the unwanted archs.
see: https://docs.sentry.io/clients/cordova/#run-script-phase

**Comment by AlejandroSilva** [comment]
@HazAT thanks, finally make it work on iOS :)
