### ISSUE TITLE
setRelease/Version/Dist not working correctly in Android

### ISSUE THREAD

**Issue by alexhisen** [getsentry/sentry-cordova#54]
Calling Sentry.setRelease, setVersion, setDist under iOS results in setting the appropriate tags in the events submitted to Sentry. But under Android, these just show up under the Additional Data section with keys like __sentry_release.

Also, these methods are undocumented.

**Comment by HazAT** [comment]
This will be fixed in the new release, coming this or next week.

**Comment by alexhisen** [comment]
setVersion() appears to have been removed in current plugin.
