### ISSUE TITLE
Sentry cordova not mentionned in https://docs.sentry.io/?

### ISSUE THREAD

**Issue by zabojad** [getsentry/sentry-cordova#55]
Why don't we see sentry-cordova in the documentation section?

<img width="299" alt="screen shot 2018-05-01 at 08 51 00" src="https://user-images.githubusercontent.com/1238030/39464311-d3bdad72-4d1c-11e8-82e7-9e7dab3d1ff1.png">

Is it something you want to drop the support?

**Comment by HazAT** [comment]
Thanks for reporting this, fixed.
And no we don't want to drop support for it, we basically just launched ^^
