### ISSUE TITLE
not usable on node 6 due to trailing commas in function parameters

### ISSUE THREAD

**Issue by yuqiora** [getsentry/sentry-cordova#58]
In #57 the hook scripts were updated and there are trailing commas in function parameters in a few places. However this is not supported by node 6 which results in `Error: unexpected token )` as soon as the plugin is added. Thus the plugin is not usable.

**Comment by HazAT** [comment]
Will fix that asap.

**Comment by yuqiora** [comment]
Thanks, that will be great.

**Comment by HazAT** [comment]
`0.10.1` is on it's way

**Comment by HazAT** [comment]
Sorry, it seems something went wrong with our release bot.
I just pushed it manually.

**Comment by yuqiora** [comment]
Finally had time to test it again. However one occurrence of trailing comma still missed at https://github.com/getsentry/sentry-cordova/blob/master/scripts/plugin_add_rm.js#L3-L4

**Comment by HazAT** [comment]
😓  `0.10.2` is on it's way
