### ISSUE TITLE
Nothing sent with no errors

### ISSUE THREAD

**Issue by hobzcalvin** [getsentry/sentry-cordova#60]
I just installed the sentry-cordova plugin and can't get it to send anything to my server. I'm monitoring network traffic and nothing happens. I have equivalent web/javascript Raven functionality working just fine pointed at the same DSN. `<access origin="*" />` in config.xml. I'm trying to debug sentry-cordova.bundle.js but there are no inline comments to help me. (The Typescript files don't look much more helpful, if I knew Typescript.)

Here's what I see from instrumenting the code with console.logs while running on an iPhone 5S:

- My code calls Sentry.captureException(e)
- exported captureException runs, uses invokeClientAsync() to run FrontendBase.prototype.captureException()
- that calls BrowserBackend.prototype.eventFromException(), which returns an __awaiter (??) with a __generator (??) that replaces existing _sendProcessedPayload with a function that sets event_1 to be the passed-in event, ready to send
- that calls the "real" Raven.captureException(), which does the actual work of processing the exception, formatting it to send over the wire, building the necessary target URL, etc.
- _send() is called, which calls _sendProcessedPayload
- _sendProcessedPayload would normally complete the send process as expected, but because it was (temporarily) set to that lambda function above, it just sets that random event_1 to be the event that would have been sent, then returns.
- We're back in the __generator which returns [2 /*return*/, normalizeRavenEvent(event_1)], theoretically to be consumed by someone somewhere, but it appears to be dropped
- the __generator restores _sendProcessedPayload to what it was originally, "cleaning up" (though it'll just be set back the next time)
- invokeClientAsync() returns, but the then() inside it is never run; the call/errorback never happens

cordova 7.1.0, cordova-ios 4.5.4. My app uses Angular. Any help appreciated, thanks.

**Comment by hobzcalvin** [comment]
Instructions for building/installing the plugin locally would also help. When I checkout the repository (to get the latest 0.10.1 changes) and try to `cordova plugin add /path/to/sentry-cordova/`, I get:
```
Installing "sentry-cordova" for android
Error during processing of action! Attempting to revert...
Failed to install 'sentry-cordova': Error: Uh oh!
ENOENT: no such file or directory, open '/path/to/my-cordova-app/plugins/sentry-cordova/dist/js/sentry-cordova.bundle.js'
```
and I'm at a loss as to how to build it. I attempted running `tsc` in the root of the plugin but got a bunch of errors:
```
src/js/Ionic/SentryIonicErrorHandler.ts:1:25 - error TS2307: Cannot find module 'sentry-cordova'.

1 import * as Sentry from 'sentry-cordova';
                          ~~~~~~~~~~~~~~~~


src/js/Ionic/SentryIonicErrorHandler.ts:2:35 - error TS2307: Cannot find module 'ionic-angular'.

2 import { IonicErrorHandler } from 'ionic-angular';
                                    ~~~~~~~~~~~~~~~


src/js/Ionic/SentryIonicErrorHandler.ts:5:15 - error TS7006: Parameter 'error' implicitly has an 'any' type.

5   handleError(error) {
                ~~~~~


src/js/__tests__/index.ts:78:11 - error TS6133: 'resolve' is declared but its value is never read.

78           resolve: (result: any) => void,
             ~~~~~~~


src/js/__tests__/index.ts:79:11 - error TS6133: 'reject' is declared but its value is never read.

79           reject: (error: any) => void,
             ~~~~~~


src/js/__tests__/index.ts:80:11 - error TS6133: 'plugin' is declared but its value is never read.

80           plugin: string,
             ~~~~~~
```

**Comment by Anakin-Hao** [comment]
Have you tried using the prive DSN url ?

**Comment by hobzcalvin** [comment]
The what? Do you mean the private instead of public DSN? IIRC all JS from a
Cordova app can be extracted, so that would not be secure...

**Comment by richardshergold** [comment]
I can't get this to work either - are [these](https://docs.sentry.io/clients/cordova/ionic/) the FULL instructions for Ionic or is there something missing?

**Comment by trfletch** [comment]
Was anyone able to get this to work, I have followed the instructions that @richardshergold posted and I can see in Fiddler that it looks like the Sentry URL is being called on a few occasions (all returning a success code of 200) but nothing shows up in the Sentry dashboard?
