### ISSUE TITLE
Mismatch app version and version in bug metadata

### ISSUE THREAD

**Issue by shaliko** [getsentry/sentry-cordova#61]
I have an issue with not working source map. After some debug I found that the issue because on mismatch app version and version in bug metadata.

1. On build app "sentry-cordova" not use app version from config.xml, instead generate another  release ID:

```
Uploading assets release: 'c007dee641852e6e3039' path: /my_projects/xxx-mobile/platforms/ios/www
```
<img width="1064" alt="release_c007dee641852e6e3039___chiplists-angular" src="https://user-images.githubusercontent.com/36139/40774092-61c8000a-64cd-11e8-88c9-388bb90a160a.png">

src/index.html
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <script>
    (function(w){var i=w.SENTRY_RELEASE=w.SENTRY_RELEASE||{};i.id='c007dee641852e6e3039';})(this);
    </script>
    <!-- sentry-cordova -->
  <meta charset="UTF-8">
...
```

config.xml
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="xxx.xxx.xxx" version="0.1.50" 
```

2. The exception from production without working source map:

<img width="1103" alt="typeerror__undefined_is_not_an_object__evaluating__e_chat_userstatistics__" src="https://user-images.githubusercontent.com/36139/40774198-ababbb12-64cd-11e8-82bb-e20fa7682581.png">

<img width="1068" alt="release_com_chiplists_mobile-0_1_50___chiplists-angular" src="https://user-images.githubusercontent.com/36139/40774238-c4fecf14-64cd-11e8-839b-6a02d98ad5f7.png">

How I can fix this mismatch with app versions

**Comment by HazAT** [comment]
Thank you for the detailed bug report! 👍 
I will take a look at it.

**Comment by shaliko** [comment]
@HazAT Hi, did you had a chance to look on it?

**Comment by HazAT** [comment]
Hey, please upgrade to latest version `0.11.0` and check if this error still exists.
Warning there are some breaking changes, check the changelog https://github.com/getsentry/sentry-cordova/releases/tag/v0.11.0

**Comment by lucacesarini** [comment]
@HazAT Hi. I'm using version `0.11.0` and I got same problem creating an android build (`ionic cordova build android --prod [--release]`): 

```
Uploading assets release: '0b727d9c9ed8ffb5913e' path: ....
```

```
file: xxxxx/platforms/android/app/src/main/assets/www/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <script>
    (function(w){var i=w.SENTRY_RELEASE=w.SENTRY_RELEASE||{};i.id='0b727d9c9ed8ffb5913e';})(this);
    </script>
    <!-- sentry-cordova -->
```

I've specified version `0.0.4` on:
- `config.xml`: `<widget id="io.ionic.starter" version="0.0.4"`
- `package.json`: `"version": "0.0.4"`
- `app.module.ts`:
```
Sentry.init({
  dsn: 'https://xxxxxxx@sentry.io/xxxxxx',
  release: "0.0.4"
});
```

**Comment by HazAT** [comment]
First of all, thank you for the detailed problem description this is 💯 
I will take a look at this and try to fix this in our script.
In the meantime you should be able to upload the artifacts a second time manually with `sentry-cli` providing the right version.

@shaliko  
It should look something like this:
`sentry-cli releases files "your-bundle-id-0.1.50" upload-sourcemaps . --dist="0.1.50"`

@lucacesarini 
For you:
`sentry-cli releases files "0.0.4" upload-sourcemaps .`

Please note that release / dist from the event have to exactly match release / dist of the release artifacts.

**Comment by HazAT** [comment]
The problem should be solved if you don't set the release for yourself. Let the SDK figure out the release by itself.

**Comment by mburger81** [comment]
@HazAT if I remove` release: '0.7.2' `from `init()` sentry does not recognize my release.

I try to use your cordova plugin with **Ionic4**, **sourcemaps** and **capacitor** framework.
