### ISSUE TITLE
Setting the environment

### ISSUE THREAD

**Issue by pbirsinger** [getsentry/sentry-cordova#62]
Not seeing this anywhere in cordova docs - how do I set the environment?

I've tried without luck:

```
      Sentry.init({
        dsn: ...,
        environment: "dev"
      })
```

**Comment by HazAT** [comment]
Hey,
Sorry for not replying earlier, I need to fix this. Will do it next week, need to update the underlying packages in order to make this work.

**Comment by pbirsinger** [comment]
Awesome - that would be life changing. Thank you!

**Comment by pbirsinger** [comment]
Any updates here? Thanks!

**Comment by HazAT** [comment]
Sorry for not keeping you up-to-date on this, we still need some time until I can make a release to make it work properly ...
But you can use a workaround for now that should work:

```
Sentry.init({
        dsn: ...,
        beforeSend: (event: SentryEvent) => {
            event.environment = "dev";
        }
});
```
Please try this.

**Comment by pbirsinger** [comment]
Tried it, but getting the following error when I add beforeSend. Doesn't happen w/o beforeSend

![screen shot 2018-06-22 at 12 02 27 pm](https://user-images.githubusercontent.com/852331/41786815-7f74ef48-7614-11e8-8a7a-3880841b093e.png)

**Comment by HazAT** [comment]
Argh, sorry my mistake you have to return the event:
```
beforeSend: (event: SentryEvent) => {
            event.environment = "dev";
            return event;
}
```

**Comment by ssalka** [comment]
@HazAT that doesn't seem to set the environment either. After inspecting the JSON of some other events (sourced from the web-based Sentry client), I found that the environment is being set via tags.

This achieves the desired result:

```ts
Sentry.init({ dsn })
Sentry.setTagsContext({ environment })
```

**Comment by aiba** [comment]
For those like me who came here trying to figure out how to set the environment, none of the above methods work anymore.

It seems you now have to call:
```js
Sentry.configureScope(function(scope) {
  scope.setTag("environment", "staging");
});
```

See #82 

It would be nice if this were documented somewhere.

**Comment by teebu** [comment]
Tried `scope.setTag("environment", "staging");` didn't work, with `"@sentry/serverless": "^5.29.2",`

This works:

```
Sentry.init({
  dsn: 'https://b....',
  environment: 'my-env',
```
