### ISSUE TITLE
Error: exec proxy not found for :: Sentry :: install

### ISSUE THREAD

**Issue by DevinCarpenter** [getsentry/sentry-cordova#65]
Not sure what I'm doing wrong. In my Cordova project I put the code needed in the project:

    onDeviceReady: function() {
        ...
        var Sentry = cordova.require("sentry-cordova.Sentry");
        Sentry.init({ dsn: '___PUBLIC_DSN___' });
        ...
    }

And  

> <access origin="sentry.io" /

> 

 in my config.xml

But each time I run the project in the browser (haven't tried other platforms) I am getting a console log

    Error: exec proxy not found for :: Sentry :: install                    cordova.js:1003:9

whereas everything else is working fine up until then. I've tested it and this is happening in Chrome and Firefox.

Any idea why? I've tried using my dsn multiple ways also and it doesn't seem to make a difference.

**Comment by HazAT** [comment]
Hey, please upgrade to latest version `0.11.0` and check if this error still exists.
Warning there are some breaking changes, check the changelog https://github.com/getsentry/sentry-cordova/releases/tag/v0.11.0

**Comment by reksc** [comment]
Experiencing the same @ ``0.12.3``

**Comment by stcktrce** [comment]
This error is still happening on `0.13.1`

**Comment by pertoft** [comment]
+1

**Comment by edwinmore1** [comment]
+1

**Comment by listentotherainbow** [comment]
Will the browser-platform be supported?

In version 0.15.0 the browser-platform is still in comments

![image](https://user-images.githubusercontent.com/53224416/63061899-23e63600-bef7-11e9-8175-79d2c0198b00.png)
