### ISSUE TITLE
Sentry.captureMessage() with Details Object?

### ISSUE THREAD

**Issue by davidofwatkins** [getsentry/sentry-cordova#68]
Hi there,

In Sentry for Javascript (Raven), I'm able to send an object with details to `captureMessage()` like so:

```js
Raven.captureMessage('This is a sample message', {
    extra: {
        details: 'This is some extra information.'
    }
});
```

However, on Cordova, the `Sentry.captureMessage()` function ONLY takes a message, so there's no way to attach extra information about it.

Is it possible to do this another way, or is this something that will be fixed?

**Comment by HazAT** [comment]
Hey, yes it's possible like this:
```javascript
Sentry.getDefaultHub().withScope(() => {
      Sentry.getDefaultHub().configureScope(scope => {
        scope.setExtra('details', 'This is some extra information.');
        Sentry.captureMessage('This is a sample message');
      });
});
```
We are still working on the documentation for the new SDKs.
While this approach seems to be more complicated than before it's also more powerful.

Hope this helps.

**Comment by davidofwatkins** [comment]
@HazAT Great, I'll give that a try, thanks!
