### ISSUE TITLE
ERROR: Plugin 'Sentry' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

### ISSUE THREAD

**Issue by richardshergold** [getsentry/sentry-cordova#69]
I'm just starting out with Sentry using it with our Ionic 3 application.

I've followed the instructions [here](https://docs.sentry.io/clients/cordova/ionic/)

And all seems to work ok on Android.

However, on iOS when I run the application on a device a watch the Xcode console I see the following errros:

```
CDVPlugin class SentryCordova (pluginName: Sentry) does not exist.
ERROR: Plugin 'Sentry' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
```

I can see the plugin in the plugins folder and in config.xml I have:

`<plugin name="sentry-cordova" spec="^0.11.0" />`

I have tried removing the iOS platform from the project and re-adding it.  That made no difference.

Any ideas what I might be doing wrong?  

(One other thing I am not sure about is whether I need to follow the instructions on the [Cordova page](https://docs.sentry.io/clients/cordova/) as well as the [Ionic page](https://docs.sentry.io/clients/cordova/ionic/) i.e do I need the init in the device/platform ready as specified on the cordova page or do I just initialise it in app.module as stated on the ionic page?)

**Comment by richardshergold** [comment]
I've removed the Cordova plugin now and am just using raven.js and all seems ok - is there any reason to use the Cordova plugin?

**Comment by HazAT** [comment]
Hey, I was just testing this and can't reproduce it.
Created a clean ionic app and added the plugin, works just fine.

The advantage of using this plugin is that you have offline caching and we also catch native device crashes.

Can you provide a minimal reproducible case so I can try to fix this issue?

**Comment by richardshergold** [comment]
Hi - it was working fine and then for some reason it stopped building (this was on iOS) so I expect if I created a new project it would work fine too.  I'm not sure what happened in my project to stop it working though as the plugin was installed ok and the config file looked ok too.

**Comment by richardshergold** [comment]
One thing I have had trouble with is removing the plugin - if you try and remove the plugin from your project does it remove cleanly with no errors?

**Comment by HazAT** [comment]
Yes, it works just fine.
Can you post the command you are running?

**Comment by richardshergold** [comment]
cordova plugin remove sentry-cordova

**Comment by richardshergold** [comment]
FYI here's my ionic info output:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v8.11.3
    npm        : 5.5.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : not set
```

**Comment by Sampath-Lokuge** [comment]
@richardshergold Are you using on-premise( i.e. we can host our own sentry server) sentry or cloud sentry?

**Comment by richardshergold** [comment]
cloud sentry

**Comment by HazAT** [comment]
I am not really sure what's going on, tried bunch of stuff but I am not able to reproduce this.
If you are able to provide a repro case I can take a look at it again.

**Comment by RaulTsc** [comment]
We are also seeing this issue. Removing sentry-cordova, removing ios and reinstalling seems to work (but I'm fighting with another issue at the moment, not sure if it's related).

Also:

```
➜  er-prism-cordova git:(develop) ✗ cordova plugin rm cordova-sqlite-storage
Sentry: running before_plugin_rm - set SENTRY_SKIP_WIZARD=true to skip this
no URL provided, fallback to https://sentry.io/
Running Sentry Wizard...
version: 0.11.0 | sentry-cli version: 1.34.0

😢  Successfully removed Sentry from your project 😢
```

Another issue that we keep having is that project.pbjxproj is sometimes overwritten with 'undefined' and I suspect it comes from sentry-cordova.

This is just feedback as I don't have time to provide reproducible examples for this. Thank you

**Comment by scottil** [comment]
Running into the same issue with "Plugin 'Sentry' not found, or is not a CDVPlugin"
