### ISSUE TITLE
no URL provided, fallback to https://sentry.io/, Running Sentry Wizard...

### ISSUE THREAD

**Issue by thibaultlavoisey** [getsentry/sentry-cordova#7]
Hello @HazAT,

I have successfully installed Sentry for Cordova/Ionic following the official documentation. However, each time I run an Ionic command (`ionic cordova emulate`, `ionic cordova build`...):

```
no URL provided, fallback to https://sentry.io/
Running Sentry Wizard...
version: 0.7.5 | sentry-cli version: 1.28.1
Sentry Wizard will you help to configure your project
Thank you for using Sentry :)
? Select the platforms you like to set up: (Press <space> to select, <a> to togg
le all, <i> to invert selection)
❯◉ iOS
 ◉ Android
```

And the CLI is KO, I must `CTRL+C` it to get out.

What's the URL? Do I need to enter it somewhere manually?

Thanks

**Comment by HazAT** [comment]
Hey, did you run `cordova plugin add @sentry/cordova` without `ionic`?
It is very important that you run this command without the `ionic` prefix.

**Comment by thibaultlavoisey** [comment]
@HazAT Yep, I did it!

Also I got the error `Error: Expected "/*", "//", or "{" but "u" found.` reported in issue #2: sometimes, the content of the file `platforms/ios/app.xcodeproj/project.pbxproj` is replaced by the string `"undefined"`, causing the error and making my iOS project KO 😱 I need to remove the platform then add it again to fix that. It's pretty inconvenient if users maked specific changes from Xcode directly.

I try to reproduce the behavior, without success 😕

Let me know how I can help you :)

**Comment by alexbonhomme** [comment]
I confirm that sentry-cli seems corrupt the `platforms/ios/app.xcodeproj/project.pbxproj` :-/

**Comment by HazAT** [comment]
Hey, I've released version `0.4.0` which fixes the issue.

**Comment by thibaultlavoisey** [comment]
Hello @HazAT, 

Thanks for your work! Which issue is fixed by the version `0.4.0`? The wizard running at each Ionic command or the `project.pbxproj` corruption?

**Comment by HazAT** [comment]
@thibaultlavoisey both should be fixed, if not I will try again (sry 😓 )
Having a hard time reproducing this.

**Comment by thibaultlavoisey** [comment]
@HazAT no problem :) I will try to reproduce ASAP and I will close this issue if it's fixed!

**Comment by HazAT** [comment]
This should be fixed in the latest version!
