### ISSUE TITLE
Use on-premise server with Ionic 3 app

### ISSUE THREAD

**Issue by Sampath-Lokuge** [getsentry/sentry-cordova#71]
Hi,

I have followed this doc: https://docs.sentry.io/clients/cordova/ionic/

We have an on-premise server for Sentry. But when I run `cordova plugin add sentry-cordova` it asks to log in to sentry.io server. So how can I use on-premise server with this plugin? Please see the attached image too.  

https://imgur.com/a/erqQ90e

`Note:` Can you tell me how to provide the on-premise url there with the plugin? I can't see anything about it on the doc.

`Note:` I have created an Angular app and its url is like so `http://sentry.myownsentryserver.com/sentry/ionic-mobile-app/` . So how can I use it with this plugin?

**Comment by HazAT** [comment]
If you run your command with `SENTRY_WIZARD_URL=http://your-url.com cordova plugin add sentry-cordova` it should work.
