### ISSUE TITLE
Getting a build error: API request failed - 403

### ISSUE THREAD

**Issue by ceaheart** [getsentry/sentry-cordova#75]
I have all of a sudden started getting an error when Sentry is uploading and updating the mappings when I build my project.  Here is the full text:

Sentry: running after_build - set SENTRY_SKIP_AUTO_RELEASE=true to skip this
Uploading assets release: 'xxx' path: C:\Users\xxx\xxx\platforms\android\app\src\main\assets\www
(node:14112) UnhandledPromiseRejectionWarning: Error: Command failed: C:\Users\xxx\xxx\node_modules\@sentry\cli\bin\sentry-cli.exe releases new xxx
error: API request failed
  caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:14112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js
process with a non-zero exit code.

**Comment by HazAT** [comment]
So this can have a few reasons.
Either you changed your auth token permissions, created a new auth token or something in your org/project has changed and your `sentry.properties` file is outdated.

Please check the content of `sentry.properties` so all the values match the ones in your `sentry.io` account.
