### ISSUE TITLE
SyntaxError: Unexpected token ':'. Parse error. ( on 0.12.1 )

### ISSUE THREAD

**Issue by GiancarloGomez** [getsentry/sentry-cordova#76]
Just updated my Sentry install and I am getting this error when I am debugging the app.

SyntaxError: Unexpected token ':'. Parse error.

<img width="585" alt="screen shot 2018-08-07 at 12 54 06 pm" src="https://user-images.githubusercontent.com/152279/43790582-00077d9c-9a41-11e8-86a9-fcf77455b728.png">

**Comment by GiancarloGomez** [comment]
Note, this does not happen with version 0.11.0 but it does with 0.12.1

**Comment by bruno333** [comment]
Same issue for me using Ionic 3.9.2.

Ionic:

   ionic (Ionic CLI)  : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0, ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   NodeJS            : v8.9.1 (/usr/local/bin/node)
   npm               : 5.5.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/e-mut/Library/Android/sdk

**Comment by HazAT** [comment]
Sorry about this, please upgrade to `0.12.2` this error should be gone.

**Comment by HazAT** [comment]
As a workaround, remove the `.map.js` file from your plugins folder of `sentry-cordova`.

**Comment by GiancarloGomez** [comment]
No worries thanks. I had done that workaround but did not want it to be a nuisance for other developers. I eventually rolled back. I will try upgrading to the latest for our next build. Thank you!

**Comment by kolya7k** [comment]
sentry-cordova 1.0.0 gives the same error... :(
