### ISSUE TITLE
Sentry: running after_build error

### ISSUE THREAD

**Issue by furaiev** [getsentry/sentry-cordova#77]
Hi there,
During building ionic app I get this error (for both ios and android builds):
`Sentry: running after_build - set SENTRY_SKIP_AUTO_RELEASE=true to skip this
Uploading assets release: '4bd4d6acee29f37ab80b' path: /Users/admin/projects/new/businessnetworkingteam1/platforms/ios/www
(node:26883) UnhandledPromiseRejectionWarning: Error: spawn /Users/admin/projects/new/businessnetworkingteam1/node_modules/@sentry/cli/sentry-cli EAGAIN
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:26883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by HazAT** [comment]
What OS are you running this at?
Also, can you make sure this file exists: `/Users/admin/projects/new/businessnetworkingteam1/node_modules/@sentry/cli/sentry-cli`

and you can run 
`./Users/admin/projects/new/businessnetworkingteam1/node_modules/@sentry/cli/sentry-cli --version`

**Comment by furaiev** [comment]
@HazAT I'm running it on macOS High Sierra 10.13.6 

The file exists:
$ /Users/admin/projects/new/businessnetworkingteam1/node_modules/@sentry/cli/sentry-cli --version
$ sentry-cli 1.34.0
