### ISSUE TITLE
Usage with `@sentry/browser`

### ISSUE THREAD

**Issue by ddoria921** [getsentry/sentry-cordova#78]
I'm trying to understand how this library integrates with `@sentry/browser` (or if it even does at all?). 

My current application is a Cordova iOS/Android app built with EmberJS. Since my app is deployed as both a hybrid mobile app and a normal SPA I'm wondering if I need to install two packages:
  1) `@sentry/browser` for the SPA
  2) `sentry-cordova` for the Cordova app

Since they're the same codebase I don't know if having both packages installed will cause some sort of conflict. What's the recommended way of setting up a project like this?

**Comment by HazAT** [comment]
There shouldn't be any conflicts if you are running both packages, but to make sure everything works fine use the pinned version of `@sentry/browser` in the `package.json` of `sentry-cordova`.

`sentry-cordova` internally uses `@sentry/browser`.

Hope this answers the question.
