### ISSUE TITLE
Sentry setRelease not working on Android

### ISSUE THREAD

**Issue by yosikal** [getsentry/sentry-cordova#80]
I'm setting the release using client.setRelease(appVersion). 

Once the release is out and I'm checking the errors status, on iOS I can filter on the release version (e.g is:unresolved release:2.8.50) while in Android the version doesn't exist and I can't find any issues.

**Comment by yosikal** [comment]
0.6.0

**Comment by HazAT** [comment]
If possible, please upgrade to the latest version, it's fixed there.
