### ISSUE TITLE
Sentry changes the SENTRY_RELEASE only after the apk has been build

### ISSUE THREAD

**Issue by blackwolf12333** [getsentry/sentry-cordova#81]
The after_build hook of this plugin changes the SENTRY_RELEASE variable on the window after building the APK. This means that the newly created release will not be associated with the apk that was just build. So you have to run your build twice to get sentry to pick up the correct release in the APK. I assume this problem also exists for iOS.

I would suggest changing the hook to before_build.

**Comment by blackwolf12333** [comment]
I assume you changed it because `ctx.opts.paths` is undefined in `after_prepare`. However that `paths` variable is not documented anywhere as far as I can tell.

**Comment by HazAT** [comment]
> Maybe not the place, but it would also be nice to be able to set an environment variable to set the release version instead of the hash you are currently using.
Good idea 👍
