### ISSUE TITLE
some methods not working after update to 0.12.2 from 0.10.2

### ISSUE THREAD

**Issue by bhumin3i** [getsentry/sentry-cordova#82]
Not Working methods : 
 
```
Sentry.setUserContext({
      email: this._userEmail
    });

 Sentry.setTagsContext({
      method: message.method,
      module: message.module
    })
```

if possible please provide full available and valid methods DOC.
i refer :  https://docs.sentry.io/clients/cordova/ 

Try using new doc i see only few methods :(   

below methods work similar?  
> Sentry.configureScope(scope => {
>       scope.setUser({  email: this._userEmail});
>     });

> Sentry.configureScope(scope => {
>       scope.setTag('method', message.method);
>       scope.setTag('module', message.module);
>     });

**Comment by HazAT** [comment]
Hey,

We had a breaking change there,
This is the way to go now:
```
Sentry.configureScope(scope => {
    scope.setUser({ email: this._userEmail});
});

Sentry.configureScope(scope => {
    scope.setTag('method', message.method);
   scope.setTag('module', message.module);
});
```
see: https://docs.sentry.io/clients/cordova/

**Comment by bhumin3i** [comment]
@HazAT thanks

**Comment by davidofwatkins** [comment]
@HazAT apologies if I'm missing something, but this API doesn't seem to be documented at https://docs.sentry.io/platforms/javascript/cordova/?

**Comment by HazAT** [comment]
@davidofwatkins Since `sentry-cordova` conforms our new unified SDK, it has the same API as all our other JavaScript SDKs.
The link I posted before is now outdated since we split it into their respective topics:
https://docs.sentry.io/learn/context/?platform=cordova

**Comment by davidofwatkins** [comment]
@HazAT Gotcha, thanks for the update!
