### ISSUE TITLE
Transporter doesn't accept builds with Sentry

### ISSUE THREAD

**Issue by Birowsky** [getsentry/sentry-cordova#86]
Recently I started getting these errors upon uploading:

```
[09:22:43]: [Transporter Error Output]: ERROR ITMS-90087: "Unsupported Architectures. The executable for TheApp.app/Frameworks/Sentry.framework contains unsupported architectures '[x86_64, i386]'."

[09:22:43]: [Transporter Error Output]: ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'TheApp.app/Frameworks/Sentry.framework/Sentry' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

[09:22:43]: [Transporter Error Output]: ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
```

I had to remove `sentry-cordova` so that I could publish the app again.

**Comment by HazAT** [comment]
I guess it's the same issue:
https://github.com/getsentry/sentry-cordova/issues/52

add this as a run script in your Xcode project.

```
# SENTRY_FRAMEWORK_PATCH
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"
    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done

    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"
    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"
done
```

**Comment by Birowsky** [comment]
@HazAT you have to agree with me that this is not a solution, but a workaround. Editing something inside the Xcode projects means editing files outside the repo. I tend to stay away from such fixes.

**Comment by HazAT** [comment]
@Birowsky Well, actually our wizard should inject this automatically into your project during setup. We are using our SDK framework built with Carthage https://github.com/Carthage/Carthage
and they do the same.
So while I agree doing changes outside VCS is bad, this should be done for you and it shouldn't be a manual process.
If this script is not injected into your Xcode project during installation it's a bug we have to fix.

**Comment by Birowsky** [comment]
@HazAT 
I think I isolated the issue: 

Adding the plugin with `cordova plugin add` makes everything work properly.

However, after freshly pulling the repo and running `cordova prepare` is when we are faced with the errors I mentioned on top. (`cordova prepare` probably doesn't run the wizard and hence doesn't add the run script?)

**Comment by HazAT** [comment]
I see, thanks for pointing this out I will think of something to fix this.

**Comment by blackwolf12333** [comment]
I just ran into this issue as well. Should this script nog be added in any case, even if the wizard isn't run?

**Comment by davidofwatkins** [comment]
I'm still seeing this issue as well. Reinstalling the plugin by itself does work, but I'm usually I'm letting Cordova download all plugins at once with `cordova platform add`. Any updates here?

**Comment by Birowsky** [comment]
@HazAT Anything interesting to report back? Or can you at least suggest a workaround to have Sentry work on CI setup?

**Comment by atroo** [comment]
We had the same problem with our CI setup and digged a little bit into the code of sentry-cordova and sentry-wizard. Actually the wizard is quite smart, when detecting whether the aformentioned fixes need to be applied to the xcode project. It runs during plugin add and also platform add. From what we saw there are 2 reasons to run into this issue:

- `SENTRY_SKIP_WIZARD` is set to `true`
- cordova platform add is executed via ionic or other commands, that do not provide TTY

Since adding the ios fixes is guarding, several executions of sentry wizard will not harm the xcode project. So to make it run in CI is as easy as:

- ionic cordova platform add ios
- ./node_modules/.bin/sentry-wizard --quiet true --integration cordova --platform ios --skip-connect true --debug true
- ionic cordova build ios

the debug flag can be left out to not pollute the log more than necessary. This can also be applied as cordova hook, since the wizard can be called from node.js, too. Hope this helps some of you guys.

**Comment by Birowsky** [comment]
@atroo thanx for sharing your findings! Could you clarify something a bit?

Say in a given CI process, the two major steps are invoked like so:

- `cordova prepare`
- `cordova build --device --release`

My guess is that whatever workaround we need to do, needs to be done after `cordova prepare` step. If correct, are you suggesting that we need to call `cordova platform add ios ...`, right after that?

**Comment by atroo** [comment]
To be honest, this is quite ionic specific. Usually I would just like to use `cordova prepare` since it is enough to generate all artifacts, but this throws an error in ionic projects and I didn't investigate it further. On a high level, you need to restore all platform and plugin state. `cordova prepare` should be enough for that. After that you need to modify the xcode project. This is what sentry-wizard does and you can call it right from the shell, since it will be installed automatically by the sentry-cordova plugin, so nothing new needed.

To strip it down, your guess is right and this should work:
```
cordova prepare
./node_modules/.bin/sentry-wizard --quiet true --integration cordova --platform ios --skip-connect true --debug true
cordova build 
```

You should be able to make it run without `cordova platform add ...`

**Comment by Birowsky** [comment]
Thanx @atroo!

If I did my research correctly, the run scripts are to be added inside this file: 

- `{cordova}/platforms/ios/{appName}.xcodeproj/project.pbxproj`

But I tried running the command you are suggesting and whatever content there was in that file, was replaced with just `undefined`.

Here’s the funny part. The build got uploaded successfully. Is this the expected behavior?

**Comment by atroo** [comment]
@Birowsky 
After executing the `sentry-wizard` command, you should open the xcodeproj in xcode. In the tab `Build Phases` there should be the 2 new run scripts added by sentry-wizard. Unfortunately it is hard to tell from here, what went wrong in your build environment. We struggeled at some points, for example, when we first added sentry with sentry-wizard, we did this in windows and the path stored in sentry.properties was broken for mac environments. So if you mix os'es in your ci environment, this could be a problem (at this point I am just guessing).

**Comment by Birowsky** [comment]
Thanx for sticking around @atroo. 

At the end of it all, I managed to fix things by implementing my own mechanism to apply the `SENTRY_FRAMEWORK_PATCH` that @HazAT referenced in the beginning of the discussion. Now everything is automated and the patch is applied as part of the CI process.

If somebody is interested in this. Let me know. I might do a PR or share the code or similar.

**Comment by atroo** [comment]
@Birowsky 
How did you apply it? I am curious what the difference is between your solution and sentry-wizard. Would be cool, if you could share it :)

**Comment by Birowsky** [comment]
[Here it is](https://gist.github.com/Birowsky/352bef7467ca79f7fd868507edcbc1f5). You just call this function with the path of the `.pbxproj` file.

[Here is the functionality](https://github.com/Birowsky/sentry-wizard/blob/master/lib/Steps/Integrations/Cordova.ts#L210) that is being replaced by this.

**Comment by atroo** [comment]
Thanks @Birowsky 
But if I see it correctly, it's the same functionality, just extracted from sentry-wizard, right? And you decided not to include the second snippet for uploading iOS debug symbols.

It's really strange, that `./node_modules/.bin/sentry-wizard --quiet true --integration cordova --platform ios --skip-connect true --debug true` is not working for you. Maybe there is some intermediate step, that changes the xcode project after this call? 

For us the sentry-wizard call is working reliably in ci. But after all at least it's running now and we all know, what is said about running systems :D

**Comment by Birowsky** [comment]
> it's the same functionality, just extracted from sentry-wizard, right?

I honestly couldn't tell whether this was the 100% intended behavior because I couldn't really understand their code. I was focused on just solving my own problem.

> And you decided not to include the second snippet for uploading iOS debug symbols.

Yeah, this thing still works in their plugin, it seems.

> Maybe there is some intermediate step, that changes the xcode project after this call.

I hope they find it and fix it :}

Cheers!

**Comment by josh-m-sharpe** [comment]
Any updates to this?  Just ran into this issue.

**Comment by danieljameswilliams** [comment]
I too have this issue

**Comment by kytwb** [comment]
This is blocking for Ionic apps using the IonicCommand build step in Azure Pipelines as the IonicCommand usually does prepare and build, so we can't quietly call run the wizard as described by @atroo. The alternative solution is to stop using the unified Ionic Command build step and use custom build steps afaik.

**Comment by studentIvan** [comment]
For some reason the build step script didn't help me with the archive architecture problem step. But the manual work with lipo did help.

```
cd ./mobile-app/platforms/ios/MyApp/Plugins/sentry-cordova/Sentry.framework
lipo -info Sentry
lipo -remove i386 Sentry -o Sentry
lipo -remove x86_64 Sentry -o Sentry
lipo -info Sentry
```

**Comment by webfletch** [comment]
Any update on this? I am using Ionic Appflow to build my iOS app then using Transporter on a Mac to upload the IPA, is there a solution that will work with the method I am using?

**Comment by ferreria23** [comment]
> Any update on this? I am using Ionic Appflow to build my iOS app then using Transporter on a Mac to upload the IPA, is there a solution that will work with the method I am using?

You can use cordova [hooks ](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/)(after_prepare) and call this [script](https://github.com/getsentry/sentry-cordova/issues/29#issuecomment-529920799). It work on Ionic 5.

**Comment by webfletch** [comment]
> You can use cordova [hooks ](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/)(after_prepare) and call this [script](https://github.com/getsentry/sentry-cordova/issues/29#issuecomment-529920799). It work on Ionic 5.

Thanks @ferreria23, very useful to know for the future, in this instance, I decided to remove Sentry completely and wrote my own custom error handler instead.

**Comment by satishmolletipipra** [comment]
I am using Ionic Appflow to build and upaload my iOS app into AppStoreConnect, but it's failed due to sentry. i'm using ionic version 3.

**Comment by webfletch** [comment]
I can't help with Sentry I'm afraid because I had the same problem so ended up removing it completely but I can give you an example of the custom error handler I wrote if that is of any help, it depends what you need to do and if you really need Sentry. The one I wrote gets the details of the error then uploads it to my API which at the moment logs it in a database (I haven't written an interface to view the errors yet) and also emails me the error.

**Comment by ericmulder** [comment]
I found that if I build the app using the --device flag Sentry only build for ARM. It actually makes sense because otherwise the app builds for the simulator which is i386. So using: `cordova build ios --release --device` I got the correct architectures to push a build to the app store.

**Comment by bruno-garcia** [comment]
Is this still an issue with the plugin version 1.0.0?
