### ISSUE TITLE
Getting Error when I run ionic cordova build ios with --release flag

### ISSUE THREAD

**Issue by neilbo** [getsentry/sentry-cordova#87]
I get this error only when I build for ios using ionic cordova and the --release flag

`Sentry: running before_compile - set SENTRY_SKIP_AUTO_RELEASE=true to skip this
Uploading assets release: '2759c00762adc892c7e2' path: /Users/neil/Projects/cardihabApp/platforms/ios/www
[13:47:10]  lint finished in 22.40 s 
(node:14501) UnhandledPromiseRejectionWarning: Error: Command failed: /Users/neil/Projects/cardihabApp/node_modules/@sentry/cli/sentry-cli releases files 2759c00762adc892c7e2 upload-sourcemaps /Users/neil/Projects/cardihabApp/platforms/ios/www/build/124.js --ignore node_modules
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 504)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:14501) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14501) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. `

**Comment by blackwolf12333** [comment]
Just try again, the sentry-cli tool sometimes throws errors which you can't do much about except just run the build again.
