### ISSUE TITLE
iOS not sending issues

### ISSUE THREAD

**Issue by ReneLems** [getsentry/sentry-cordova#88]
My implementation is not sending issues to our company's on-premise Sentry implementation. I've allowed our domain in the config.xml. And everything is working fine on Android. By debugging I saw that the sentry code is reached, but I couldn't really figure out the `sentry-cordova.bundle.js` code.

This is the code in my project I'm using for testing at the moment, which is called on `deviceready`:
````
    window.Sentry = cordova.require('sentry-cordova.Sentry');
    window.Sentry.init({
      dsn: 'https://1234567890@sentry.company.com/10'
    });
    setTimeout(() => {
      console.log('capture message');
      window.Sentry.captureMessage('HOI!!!');
      try {
        throw new Error('test');
      } catch (e) {
        console.log('catch exception', e);
        window.Sentry.captureException(e);
      }
    }, 3000)
````

In the debugger area of Xcode(9.4.1) I do see the following extra output when I enable the sentry-cordova plugin:
```
 [BoringSSL] Function boringssl_session_errorlog: line 2871 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
```
Unfortunately, searching on Google for this hasn't made me any wiser.

Any clue as to what the problem might be?

Using version 0.12.3, but also tried using 0.11.0 and 0.10.*

**Comment by FishSaidNo** [comment]
Could be caused by lionheart/openradar-mirror#19881 ?

This ~~was~~ still is an issue for me with sentry/browser. Temporary solution is to use http not https in the DSN.
