### ISSUE TITLE
after_prepare hook does only upload 5 hardcoded js source files and sourcemaps

### ISSUE THREAD

**Issue by DavidStrausz** [getsentry/sentry-cordova#9]
https://github.com/getsentry/sentry-cordova/blob/5be9e09eb7dd459c2c2ba88f822accba9167a986/scripts/after_prepare.js#L51

This works pretty well for a standard ionic/cordova project without different bundles, in a more advanced scenario there are multiple bundles with their own sourcemap, e.g.

- 0.js
- 0.js.map
- 1.js
- 1.js.map
- 2.js
- 2.js.map
- ...

To also cover this scenario the files uploaded to a release should not be predefined, the build directory should be looped through. Something like this should do the trick:

```js
// Adding files to include
let includes = [];
fs.readdir(buildPath, function (error, files) {
  if (error) {
    console.error('Could not list files of build directory: ', buildPath);
  }

  files.forEach(function(file, index) {
    let f = path.basename(file);
    let [name, ext1, ext2] = f.split('.');
    // we only want js source files and the according sourcemaps (no css etc.)
    if (ext1 === 'js' || (ext1 === 'js' && ext2 === 'map')) {
      // ignore sw-toolbox file
      if (name !== 'sw-toolbox') {
        includes.push(path.join(buildPath, f));  
      }
    }
  });
});
```

**Comment by HazAT** [comment]
Thx for this.
Releasing new version with your code today 👍
