### ISSUE TITLE
Debug symbol upload started / finished - when? why? disable?

### ISSUE THREAD

**Issue by Tallyb** [getsentry/sentry-cordova#90]
When building the app in xcode, I get notification that the debug symbols upload started / finished. 
so: 
a) Where are those files visible on sentry? What release do they match? 
b) Is there a way to disable it, so not every build by each developer in the team will upload new files?

**Comment by HazAT** [comment]
You can find the files in your project settings under Debug Files.
dSYMs do not have to to be assigned to a release, we match them via the UUID.
You can disable it by changing the run script phase in your Xcode project.
