### ISSUE TITLE
Failed to restore plugin "sentry-cordova" from config.xml.

### ISSUE THREAD

**Issue by ddoria921** [getsentry/sentry-cordova#91]
I'm getting failures installing `sentry-cordova` through our CI builds. The exact error is

```
Saved plugin info for "sentry-cordova" to config.xml
Sentry: running after_plugin_add - set SENTRY_SKIP_WIZARD=true to skip this
Failed to restore plugin "sentry-cordova" from config.xml.
You might need to try adding it again.
Error: Error: Cannot find module '/Users/Darin/Development/mobile-app/cordova/package.json'
```

Out of all the plugins, this is the only one that fails because `package.json` is missing in the cordova directory. We don't check in cordova's `package.json` because it installs the plugins from `config.xml`. During the install process I also ran it with `SENTRY_SKIP_WIZARD=true`. 

I think the issue is [here in this file ](https://github.com/getsentry/sentry-cordova/blob/master/scripts/plugin_add_rm.js#L11). It's requiring some modules (which checks in package.json) and then skipping the install anyway. Changing it to check for the `SENTRY_SKIP_WIZARD` flag first may fix the issue. 

I'm proposing changing the order of execution so it looks like this
```javascript
module.exports = function(ctx) {
  try {
    if (!ctx.opts.plugins.some(plugin => plugin.includes('sentry-cordova'))) {
      return;
    }
  } catch (e) {}

  console.log(
    `Sentry: running ${ctx.hook} - set SENTRY_SKIP_WIZARD=true to skip this`
  );

  if (process.env.SENTRY_SKIP_WIZARD) {
    console.log('Sentry: Skipping Sentry Wizard');
    return;
  }

  // do `require` if we're not skipping sentry wizard
  const wizard = require('@sentry/wizard');
  const tty = require('tty');
  const fs = ctx.requireCordovaModule('fs');

  // rest of code ...
```

I'm happy to open a PR for this if you're open to making this change.

**Comment by patryk-fuhrman** [comment]
I have the same issue on CI. Any updates on this?

**Comment by edwinmore1** [comment]
+1

**Comment by HazAT** [comment]
Will fix this in the next release 👍
