### ISSUE TITLE
Disabling Sentry auto release

### ISSUE THREAD

**Issue by JoaoSouMoreira** [getsentry/sentry-cordova#92]
Is there any other way to disable this behaviour besides setting an environment variable?

We have our own build pipeline that explicitly creates a release and uploads the source maps to Sentry on every release, we also use custom release versions for this.

I would rather be able to set some sort of configuration somewhere (as a variable in `config.xml`?) than having each of the developers working on our project make sure they have the environment variable on their systems.

Note - I am aware that as an immediate solution I can create a `before_prepare` hook and set `process.env.SENTRY_SKIP_AUTO_RELEASE = TRUE` there. I just feel like we could use a simpler method of configuring this.

**Comment by adipascu** [comment]
This would if we had a cordova variable instead of an environment variable.
See the docs here: https://cordova.apache.org/docs/en/8.x/config_ref/index.html#variable
This is also used in other plugins like [facebook4](https://github.com/jeduan/cordova-plugin-facebook4)

**Comment by kodeine** [comment]
@JoaoSouMoreira can you tell me how you've put `process.env.SENTRY_SKIP_AUTO_RELEASE = TRUE` i put it under hooks/before_prepare/000_skip_sentry_release.js` but its not working for me. it keeps on pushing data to sentry.
