### ISSUE TITLE
Getting 404 

### ISSUE THREAD

**Issue by HamzaLJ** [getsentry/sentry-cordova#93]
When launching the app in production mode it throws the following :

> http://localhost:8080/var/containers/Bundle/Application/A416BAEF-F864-4A43-8620-6E49393EA3BB/Kanakol.app/www/plugins/sentry-cordova/dist/js/sentry-cordova.bundle.js.map
> Failed to load resource: the server responded with a status of 404 (Not Found)

I am using Ionic 3.9.2 along with cordova 7.1.0 

I've tested only in an iPhone device and got that error.

**Comment by TyGuy** [comment]
Same issue here. Ionic 3.9.2, Cordova 8.1. Happy to share a more complete `package.json` if that's useful.

**Comment by mjsarfatti** [comment]
Same here.

**Comment by rafwell** [comment]
+1
