### ISSUE TITLE
How to send a warning?

### ISSUE THREAD

**Issue by aiba** [getsentry/sentry-cordova#96]
I'd like to be able to capture a message with level="warning".  Is there a way to do this with this API?

**Comment by HazAT** [comment]
With `0.13.0` you can call `Sentry.captureMessage('message', 'warning');` 🎉

**Comment by aiba** [comment]
Not sure if this is the culprit, but it looks like Raven.captureMessage takes the map `{level: 'warning'}` as the second argument, not `'warning'` as a bare string.  Could this be the issue?

**Comment by HazAT** [comment]
@aiba Sorry, I've released `0.13.1` this should fix the issue.

**Comment by HazAT** [comment]
We changed the API from raven-js -> sentry-cordova, we no longer accept an object as a second arg.

**Comment by aiba** [comment]
It works!  @HazAT thank you so much!!! :) :) :)
