### ISSUE TITLE
Hint parameter in eventprocessors/beforeSend

### ISSUE THREAD

**Issue by Mike1707** [getsentry/sentry-cordova#97]
Hey Guys!

In the javascript docs for the event processing (https://docs.sentry.io/platforms/javascript/#eventprocessors) there is a parameter called "hint".  I'm not able to use this parameter with sentry-cordova.

My initial problem is that I run into the same issue as in this repo described https://github.com/getsentry/react-native-sentry/issues/391 and I would like to implement this workaround https://github.com/getsentry/react-native-sentry/issues/391#issuecomment-431344211.

Is there any solution? 

Regards,
Mike

**Comment by HazAT** [comment]
`0.13.0` now shipped with this feature
