### ISSUE TITLE
Cordova browser platform not supported?

### ISSUE THREAD

**Issue by shnist** [getsentry/sentry-cordova#98]
Hi,

We have an Ionic V3 project that was using raven-js and we wanted to migrate to the new sentry-cordova plugin.

We followed the installation guide here https://docs.sentry.io/platforms/javascript/ionic/. For Android and iOS this works fine.

However when we try and use it with the Browser platform we get an infinite loop of the following message:

`Error: exec proxy not found for :: Sentry :: addBreadcrumb`

I was able to reproduce this on an Ionic starter application too, which is here: https://github.com/shnist/sentry-browser-platform. 

Steps to reproduce:
* Clone https://github.com/shnist/sentry-browser-platform
* Install ionic cli `npm i ionic -g`
* `npm i`
* `ionic cordova run browser`

Let me know if you require any more information.
Thanks

**Comment by andrewvmail** [comment]
I am also seeing this issue, work around i just have i use raven when i detect its running in desktop.

**Comment by reksc** [comment]
Same here for bare-bones cordova app

**Comment by richardshergold** [comment]
I was about to migrate from raven to the plugin too but our app is ios, android and web - will hold off if this is an issue?

**Comment by seza443** [comment]
Same issue with Ionic 4

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/home/user/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/user/Softwares/android-sdk/Sdk)
   NodeJS            : v8.11.3 (/home/user/.nvm/versions/node/v8.11.3/bin/node)
   npm               : 6.5.0
   OS                : Linux 4.15
```

**Comment by pertoft** [comment]
+1

**Comment by Polm90** [comment]
Same issue with cordova 9.0.0 and cordova-browser 6.0.0.

It seems that electron is not supported too (electron falls back on browser)

**Comment by casyalex** [comment]
same with cordova 8.0, really need browser platform for dev

**Comment by richardshergold** [comment]
Is this still an issue?

**Comment by Polm90** [comment]
Yes

**Comment by ludufre** [comment]
+1

**Comment by phihochzwei** [comment]
+1 Same here

**Comment by Polm90** [comment]
Still an issue with cordova 10...

any solution available?

**Comment by kyledef** [comment]
Still have the issues on `"sentry-cordova": "^0.17.0"`
